UBSan CppunitTest_sw_writerfilter_misc needs the SwXStyleFamilies now
...presumably since f13e5718f53c3e460a6aacdb8f429d18ac011fa3 "use more concrete
UNO type in writerfilter":

> DynamicLibraryManagerException: "Failed to load dynamic library: /home/sberg/lo/core/workdir/LinkTarget/CppunitTest/libtest_sw_writerfilter_misc.so
> /home/sberg/lo/core/instdir/program/libsw_writerfilterlo.so: undefined symbol: _ZTI16SwXStyleFamilies"

Change-Id: I55014caff2c7b662edf1a552e496d4c9955ce23e
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/171468
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>
Tested-by: Jenkins