mkdir_p still needed by make create-partial-info
157298bb808a943616991927f9370a86c1f2ca48 "android and bin/update: make pythonic"
had removed it, so that `make create-partial-info` would now fail at least with

> Traceback (most recent call last):
>   File "bin/update/create_partial_update.py", line 10, in <module>
>     from path import UpdaterPath, mkdir_p, convert_to_unix, convert_to_native
> ImportError: cannot import name 'mkdir_p' from 'path' (bin/update/path.py)

(and no idea if that make target would still do anything useful, beyond this
initial hurdle)

Change-Id: Ib1be3304e2b3468dc187c1b5e24041e68a3677fc
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/160397
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>