qt: Include QtTools header in QtPainter.hxx
Required for `scaledQRect`.
Fixes this build failure seen on Windows with
Hossein's WIP Gerrit change [1]:

    C:\Users\mwegh\development\git\libreoffice\vcl\inc\qt6\../qt5/QtPainter.hxx(46): error C3861: 'scaledQRect': identifier not found

[1] https://gerrit.libreoffice.org/c/core/+/199615

Change-Id: I8a8e21c6aedf8ab29a0f228887ac1f82928aa687
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/200194
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>
Tested-by: Jenkins