sw: Dereferencing NULL pointer 'pChangeHint'
After
commit c239b6cad271d20f443482bc8b6039b1734d18f2
Author: Noel Grandin <noelgrandin@gmail.com>
Date:   Sat Jan 4 16:20:57 2025 +0200

    convert RES_ATTRSET_CHG to SfxHint

C:/cygwin/home/tdf/lode/jenkins/workspace/lo_tb_master_win_analyze/sw/source/core/draw/dcontact.cxx(1670): error C2220: the following warning is treated as an error
C:\cygwin\home\tdf\lode\jenkins\workspace\lo_tb_master_win_analyze\sw\source\core\draw\dcontact.cxx(1529) : warning C6011: Dereferencing NULL pointer 'pChangeHint->m_pNew'. : Lines: 1415, 1416, 1417, 1424, 1431, 1433, 1435, 1436, 1437, 1445, 1447, 1448, 1450, 1454, 1496, 1499, 1500, 1525, 1528, 1529

C: /cygwin/home/tdf/lode/jenkins/workspace/lo_tb_master_win_analyze/sw/source/core/fields/docufld.cxx(2318): error C2220: the following warning is treated as an error
C: \cygwin\home\tdf\lode\jenkins\workspace\lo_tb_master_win_analyze\sw\source\core\fields\docufld.cxx(2294) : warning C6011: Dereferencing NULL pointer 'pChangeHint'. : Lines: 2265, 2271, 2273, 2274, 2275, 2276, 2290, 2279, 2294
Change-Id: I919d59d108a39dd77adb18967392a8ae8920275a
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/180431
Reviewed-by: Noel Grandin <noel.grandin@collabora.co.uk>
Tested-by: Jenkins
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>