Make vcl::bitmap::get_unpremultiply_table VCL_DLLPUBLIC again
This fixes my GCC 13.2.0 --enable-gtk4 build on Debian
testing, which started failing after

    commit acd40306b3737d50cf24462b2d3e451092543e64
    Date:   Thu Mar 14 12:22:13 2024 +0200

        reduce symbol visibility in vcl

like this:

    /home/michi/development/git/libreoffice-WORKTREE/vcl/unx/gtk4/../gtk3/salnativewidgets-gtk.cxx:2195: error: undefined reference to 'vcl::bitmap::get_unpremultiply_table()'
    collect2: error: ld returned 1 exit status
    make[1]: *** [/home/michi/development/git/libreoffice-WORKTREE/vcl/Library_vclplug_gtk4.mk:20: /home/michi/development/git/libreoffice-WORKTREE/instdir/program/libvclplug_gtk4lo.so] Error 1
    make[1]: *** Waiting for unfinished jobs....
    make: *** [Makefile:290: build] Error 2

Change-Id: I0921801f6ad0f20f5250ca15a2749d7da044fcd8
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/164856
Tested-by: Jenkins
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>