workaround loplugin:cppunitassertequals
There is no operator<< for SfxPoolItem, so a straightforward convert to
CPPUNIT_ASSERT_EQUAL is not possible.

/home/noel/libo/sw/qa/extras/tiledrendering/tiledrendering.cxx:2725:5:
error: rather call CPPUNIT_ASSERT_EQUAL when comparing 'const
SfxPoolItem' and 'SvxWeightItem' (or rewrite as an explicit operator ==
call when the operator itself is the topic)
[loplugin:cppunitassertequals]
 2725 |     CPPUNIT_ASSERT(*pPoolItem == aBoldWeightItem); // a bold
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Change-Id: Ia92779d54d252245e1d3b8e32c574e4226342f36
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/175771
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>