tdf#130857 sc: Merge checkbox and text column in "Protect Sheet" dialog
As the weld::TreeView doc says, two special "expander" columns
for toggle buttons and images can be used that can be accessed
by index -1 in the weld::TreeView API:

    /* Model column indexes are considered to begin at 0, but with special columns
       before index 0. A expander image column (and an additional optional toggle
       button column when enable_toggle_buttons is used). Column index -1 is
       reserved to access those columns.
    */
    class VCL_DLLPUBLIC TreeView : virtual public ItemView

While the vcl implementation in SalInstanceTreeView doesn't
currently take into account the .ui file at all, the gtk3
vcl implementation (GtkInstanceTreeView) does and the
native Qt implementation in QtInstanceTreeView also does.

If the special toggle renderer is used in the first
column, the next "real" renderer still uses column index 0
in the weld API.
That makes sense if the renderer is actually
in the first column still, but is rather
non-obvious/confusing if that's not the case.
(For the column indices to use in the weld API,
the GtkInstanceTreeView ctor currently unconditionally
considers a GtkCellRendererToggle to be a special expander
"column" when it is the first renderer in
the first column, regardless of whether more
renderers are there or not, so column index 0
is still available for the next renderer.)

Having the special toggle renderer in its own column
but still using a column index of 0 for the text that
is then supposed to be in actual column 1 doesn't
play well with the qt6 vcl plugin with native widgets
used (SAL_VCL_QT_USE_WELDED_WIDGETS=1), as that one uses
the actual columns as defined in the .ui file
(and corresponding column indices of 0 for the first
column, 1 for the next column,...) to set/retrieve conent
other than the "special expander columns".

As a consequence, the Calc "Protect Sheet"
dialog  would show both, the checkbox and the text in
column 0 and column 1 would just be empty
(but still consume space, i.e. make the dialog look
a bit odd).

The dialog can be triggered like this:

* start Calc
* right-click on "Sheet1" in the tab bar at the bottom
* select "Protect Sheet..." menu entry

Improve this by merging the 2 existing columns into
one, i.e. moving the GtkCellRenderer for the text
into the first column instead of having an own
GtkTreeViewColumn by itself.

This gets rid of the unused extra column for the
qt6 vcl plugin with native widgets in used.
No noticeable difference was seen with the gtk3 or gen
vcl plugins in a quick test.

This case was found by running the ui-rules-enforcer
with upcoming commit

    Change-Id: Ib596c39698d308e18e9ede27c239cd44e43863a9
    Author: Michael Weghorn <m.weghorn@posteo.de>
    Date:   Fri Jun 19 08:58:59 2026 +0200

        tdf#130857 ui-rules-enforcer: Check that special toggle renderer not by itself

in place:

    Exception: ('sc/uiconfig/scalc/ui/protectsheetdlg.ui: expander toggle cell renderer by itself in first column: ', 'checklist')

In general:

Since the special toggle button is to toggle an
entry on/off, it also makes sense if it is in the
same column as the icon or text that it enables/disables.
If there any cases where the button should actually be
in its own column, then it would in my opinion
make more sense to also use a regular column index of 0 instead
of the "expander toggle column" feature (with a column index of -1).
Allowing to do that would require more rework (as it would
break the current assumption/logic in the GtkInstanceTreeView ctor
as described above). If there are any cases where it
makes sense to have the renderer in its own column
by itself, supporting that use case with a column
index of 0 (instead of the current -1) should be easier to
implement in the future once all cases where different columns
aren't needed (like the one addressed by this commit) have been
handled first. (Then, the logic in the GtkInstanceTreeView ctor
can be adjusted without breaking those.)

Change-Id: I51302dbd96f3e8b23fcbd96855d01b489acd2c6b
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/207030
Tested-by: Jenkins
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>