qt: Include QtTools header in QtFrame.cxx
Required for `toColor` and more helper functions.

Fixes build failures like this one seen on Windows
when experimenting with Hossein's WIP Gerrit change [1]:

    C:\Users\mwegh\development\git\libreoffice\vcl\qt6\../qt5/QtFrame.cxx(1036): error C3861: 'toColor': identifier not found

[1] https://gerrit.libreoffice.org/c/core/+/199615

Change-Id: I9f118c37989d2d3d489d553cf8258418875e20cc
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/200229
Tested-by: Jenkins
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>