boost: upgrade to 1_88_0
* external/boost/armv7.patch.0 and
external/boost/0001-Avoid-Wdeprecated-variadic-comma-omission-with-GCC-1.patch.2
have been fixed upstream

* ignore warning 4996 in vcl/source/window/layout.cxx, otherwise it started to fail with
[build CXX] vcl/source/window/layout.cxx
C:\cygwin64\home\tdf\jenkins\workspace\gerrit_windows\workdir\UnpackedTarball\boost\boost/multi_array/storage_order.hpp(51): error C2220: the following warning is treated as an error
C:\cygwin64\home\tdf\jenkins\workspace\gerrit_windows\workdir\UnpackedTarball\boost\boost/multi_array/storage_order.hpp(51): warning C4996: 'boost::array<bool,2>::assign': please use `fill` instead
C:\cygwin64\home\tdf\jenkins\workspace\gerrit_windows\workdir\UnpackedTarball\boost\boost/multi_array/storage_order.hpp(47): note: while compiling class template member function 'boost::general_storage_order<2>::general_storage_order(const boost::c_storage_order &)'
C:\cygwin64\home\tdf\jenkins\workspace\gerrit_windows\workdir\UnpackedTarball\boost\boost/multi_array.hpp(153): note: see reference to function template instantiation 'boost::general_storage_order<2>::general_storage_order(const boost::c_storage_order &)' being compiled
C:\cygwin64\home\tdf\jenkins\workspace\gerrit_windows\workdir\UnpackedTarball\boost\boost/multi_array/multi_array_ref.hpp(350): note: see reference to class template instantiation 'boost::general_storage_order<2>' being compiled
C:\cygwin64\home\tdf\jenkins\workspace\gerrit_windows\workdir\UnpackedTarball\boost\boost/multi_array/multi_array_ref.hpp(414): note: see reference to class template instantiation 'boost::const_multi_array_ref<T,2,T *>' being compiled
        with
        [
            T=`anonymous-namespace'::GridEntry
        ]
C:\cygwin64\home\tdf\jenkins\workspace\gerrit_windows\workdir\UnpackedTarball\boost\boost/multi_array.hpp(122): note: see reference to class template instantiation 'boost::multi_array_ref<T,2>' being compiled
        with
        [
            T=`anonymous-namespace'::GridEntry
        ]
C:/cygwin64/home/tdf/jenkins/workspace/gerrit_windows/vcl/source/window/layout.cxx(905): note: see reference to class template instantiation 'boost::multi_array<`anonymous-namespace'::GridEntry,2,std::allocator<T>>' being compiled
        with
        [
            T=`anonymous-namespace'::GridEntry
        ]
C:\cygwin64\home\tdf\jenkins\workspace\gerrit_windows\workdir\UnpackedTarball\boost\boost/multi_array/multi_array_ref.hpp(343): warning C4996: 'boost::array<int,2>::assign': please use `fill` instead
C:\cygwin64\home\tdf\jenkins\workspace\gerrit_windows\workdir\UnpackedTarball\boost\boost/multi_array/multi_array_ref.hpp(325): note: while compiling class template member function 'boost::const_multi_array_ref<T,2,T *>::const_multi_array_ref(TPtr,const boost::general_storage_order<2> &,const int *,const unsigned int *)'
        with
        [
            T=`anonymous-namespace'::GridEntry,
            TPtr=`anonymous-namespace'::GridEntry *
        ]
C:\cygwin64\home\tdf\jenkins\workspace\gerrit_windows\workdir\UnpackedTarball\boost\boost/multi_array/multi_array_ref.hpp(616): note: see reference to function template instantiation 'boost::const_multi_array_ref<T,2,T *>::const_multi_array_ref(TPtr,const boost::general_storage_order<2> &,const int *,const unsigned int *)' being compiled
        with
        [
            T=`anonymous-namespace'::GridEntry,
            TPtr=`anonymous-namespace'::GridEntry *
        ]
C:\cygwin64\home\tdf\jenkins\workspace\gerrit_windows\workdir\UnpackedTarball\boost\boost/multi_array/view.hpp(234): warning C4996: 'boost::array<int,2>::assign': please use `fill` instead
C:\cygwin64\home\tdf\jenkins\workspace\gerrit_windows\workdir\UnpackedTarball\boost\boost/multi_array/view.hpp(434): note: see reference to function template instantiation 'boost::detail::multi_array::const_multi_array_view<T,2,T *>::const_multi_array_view<ExtentList,int>(TPtr,const ExtentList &,const boost::array<int,2> &)' being compiled
        with
        [
            T=`anonymous-namespace'::GridEntry,
            ExtentList=boost::array<int,2>,
            TPtr=`anonymous-namespace'::GridEntry *
        ]
C:\cygwin64\home\tdf\jenkins\workspace\gerrit_windows\workdir\UnpackedTarball\boost\boost/multi_array/view.hpp(434): note: see reference to function template instantiation 'boost::detail::multi_array::const_multi_array_view<T,2,T *>::const_multi_array_view<ExtentList,int>(TPtr,const ExtentList &,const boost::array<int,2> &)' being compiled
        with
        [
            T=`anonymous-namespace'::GridEntry,
            ExtentList=boost::array<int,2>,
            TPtr=`anonymous-namespace'::GridEntry *
        ]
C:\cygwin64\home\tdf\jenkins\workspace\gerrit_windows\workdir\UnpackedTarball\boost\boost/multi_array/base.hpp(490): note: see reference to function template instantiation 'boost::detail::multi_array::multi_array_view<T,2>::multi_array_view<boost::array<int,2>,int>(T *,const ExtentList &,const boost::array<int,2> &)' being compiled
        with
        [
            T=`anonymous-namespace'::GridEntry,
            ExtentList=boost::array<int,2>
        ]
C:\cygwin64\home\tdf\jenkins\workspace\gerrit_windows\workdir\UnpackedTarball\boost\boost/multi_array/base.hpp(487): note: see reference to function template instantiation 'boost::detail::multi_array::multi_array_view<T,2>::multi_array_view<boost::array<int,2>,int>(T *,const ExtentList &,const boost::array<int,2> &)' being compiled
        with
        [
            T=`anonymous-namespace'::GridEntry,
            ExtentList=boost::array<int,2>
        ]
C:\cygwin64\home\tdf\jenkins\workspace\gerrit_windows\workdir\UnpackedTarball\boost\boost/multi_array/multi_array_ref.hpp(539): note: see reference to function template instantiation 'ArrayRef boost::detail::multi_array::multi_array_impl_base<T,2>::generate_array_view<return_type,2,`anonymous-namespace'::GridEntry*>(boost::type<return_type>,const boost::detail::multi_array::index_gen<2,2> &,const unsigned int *,const int *,const int *,TPtr) const' being compiled
        with
        [
            ArrayRef=return_type,
            T=`anonymous-namespace'::GridEntry,
            TPtr=`anonymous-namespace'::GridEntry *
        ]
C:\cygwin64\home\tdf\jenkins\workspace\gerrit_windows\workdir\UnpackedTarball\boost\boost/multi_array/multi_array_ref.hpp(533): note: see reference to function template instantiation 'ArrayRef boost::detail::multi_array::multi_array_impl_base<T,2>::generate_array_view<return_type,2,`anonymous-namespace'::GridEntry*>(boost::type<return_type>,const boost::detail::multi_array::index_gen<2,2> &,const unsigned int *,const int *,const int *,TPtr) const' being compiled
        with
        [
            ArrayRef=return_type,
            T=`anonymous-namespace'::GridEntry,
            TPtr=`anonymous-namespace'::GridEntry *
        ]
C:\cygwin64\home\tdf\jenkins\workspace\gerrit_windows\workdir\UnpackedTarball\boost\boost/multi_array.hpp(494): note: see reference to function template instantiation 'boost::detail::multi_array::multi_array_view<T,2> boost::multi_array_ref<T,2>::operator []<2>(const boost::detail::multi_array::index_gen<2,2> &)' being compiled
        with
        [
            T=`anonymous-namespace'::GridEntry
        ]
C:\cygwin64\home\tdf\jenkins\workspace\gerrit_windows\workdir\UnpackedTarball\boost\boost/multi_array.hpp(494): note: see reference to function template instantiation 'boost::detail::multi_array::multi_array_view<T,2> boost::multi_array_ref<T,2>::operator []<2>(const boost::detail::multi_array::index_gen<2,2> &)' being compiled
        with
        [
            T=`anonymous-namespace'::GridEntry
        ]
C:\cygwin64\home\tdf\jenkins\workspace\gerrit_windows\workdir\UnpackedTarball\boost\boost/multi_array.hpp(454): note: while compiling class template member function 'boost::multi_array<`anonymous-namespace'::GridEntry,2,std::allocator<T>> &boost::multi_array<T,2,std::allocator<T>>::resize(const boost::detail::multi_array::extent_gen<2> &)'
        with
        [
            T=`anonymous-namespace'::GridEntry
        ]
C:/cygwin64/home/tdf/jenkins/workspace/gerrit_windows/vcl/source/window/layout.cxx(928): note: see reference to function template instantiation 'boost::multi_array<`anonymous-namespace'::GridEntry,2,std::allocator<T>> &boost::multi_array<T,2,std::allocator<T>>::resize(const boost::detail::multi_array::extent_gen<2> &)' being compiled
        with
        [
            T=`anonymous-namespace'::GridEntry
        ]
make[1]: *** [C:/cygwin64/home/tdf/jenkins/workspace/gerrit_windows/solenv/gbuild/LinkTarget.mk:339: C:/cygwin64/home/tdf/jenkins/workspace/gerrit_windows/workdir/CxxObject/vcl/source/window/layout.o] Error 2

<https://dev-www.libreoffice.org/src/boost_1_88_0.tar.xz> has been generated (on
Debian 12) with

> $ wget https://boostorg.jfrog.io/artifactory/main/release/1.88.0/source/boost_1_88_0.tar.bz2
> $ printf '46d9d2c06637b219270877c9e16155cbd015b6dc84349af064c088e9b5b12f7b boost_1_88_0.tar.bz2' | sha256sum -c # cf. <https://www.boost.org/users/history/version_1_88_0.html>
> boost_1_88_0.tar.bz2: OK
> $ external/boost/repack_tarball.sh boost_1_88_0.tar.bz2
> Unpacking boost_1_88_0.tar.bz2 ...
> Removing unnecessary files ...
> Creating boost_1_88_0.tar.xz ...
> Cleaning up ...
> 5c67a448c562f1606e38203ba7ed7e8d7453581b6b9ca324e96205eae0da5ff8  boost_1_87_0.tar.xz
> Done.

Change-Id: Ib5f613b34ffb161348b1fd7653cce0d12da98994
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/184035
Tested-by: Jenkins
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>