Disable flakey navigator UITest again
f2ba17fecb60d936599efb975d96a3ea06c2a43f "disable more flakey navigator UITest",
then 0a0c5a5b0521bea6cb695731d448e62c41ed4c57 "UITest_sw_navigator: avoid
oneprocess" enabled it again, apparently in the false hopes that non-oneprocess
would magically fix this issue.  But this still causes frequent failures, e.g.,
<https://ci.libreoffice.org//job/lo_ubsan/2974/> failed with

> ======================================================================
> FAIL: test_tdf134390 (navigator.navigator)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/tdf/lode/jenkins/workspace/lo_ubsan/sc/qa/uitest/calc_tests8/navigator.py", line 145, in test_tdf134390
>     self.assertEqual(get_state_as_dict(xColumn)['Value'], '2')
> AssertionError: '1' != '2'
> - 1
> + 2

and <https://ci.libreoffice.org//job/lo_ubsan/2975/> failed with

> ======================================================================
> FAIL: test_tdf134390 (navigator.navigator)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/tdf/lode/jenkins/workspace/lo_ubsan/sc/qa/uitest/calc_tests8/navigator.py", line 145, in test_tdf134390
>     self.assertEqual(get_state_as_dict(xColumn)['Value'], '2')
> AssertionError: '53' != '2'
> - 53
> + 2

Change-Id: I39e878c20085cca3233f7c8859b9a1d28fcc56c8
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/159262
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>