Fix setting nullopt to the optional autocorrect entries
Trying to replace the manual management of settings in testTdf151801
with ScopedConfigValue, I found out that it broke other tests there:

 C:/lo/core/sw/qa/extras/autocorrect/autocorrect.cxx(64) : error : Assertion
 Test name: testTdf38394::TestBody
 equality assertion failed
 - Expected: l’« 
 - Actual  : l‹ »

 C:/lo/core/sw/qa/extras/autocorrect/autocorrect.cxx(45) : error : Assertion
 Test name: testTdf92029::TestBody
 equality assertion failed
 - Expected: Ik ben ’s morgens opgestaan
 - Actual  : Ik ben ›s morgens opgestaan

It looked like restoring the settings in ScopedConfigValue dtor had
no effect. But manually testing the restored values using officecfg
demonstrated that it worked as expected: the optional value appeared
empty, as before the test.

It turned out, that the problem was in SvxBaseAutoCorrCfg::Load: it
listened to the registry changes, but only loaded new value, when
it was not empty, meaning that setting a non-empty value, and then
resetting it back to empty would keep the last non-empty value in
SvxAutoCorrCfg.

This change modifies SvxBaseAutoCorrCfg::Load to properly handle
empty values. Booleans are now checked using Any::operator==(bool),
which checks the type. For other values, the usual operator >>= is
used, which is simply no-op for empty Any.

testTdf151801 is modified to use ScopedConfigValue.

Change-Id: Ia3f413583541cde482db234fe73d7f665be507ae
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/198502
Reviewed-by: Mike Kaganski <mike.kaganski@collabora.com>
Tested-by: Jenkins