sc: Add missing TreeView include in tpusrlst.hxx
Without this, Qt Creator shows this error/warning
when opening the header:

    tpusrlst.hxx:49:27: No member named 'TreeView' in namespace 'weld' (fix available)

(Probably not a problem during the build because of
the header only being included after other includes
that provide weld::TreeView transitively, but that
shouldn't be necessary.)

Change-Id: I4c542fa025dd4fb71e15ea9bab181954a12c853b
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/207914
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>
Tested-by: Jenkins