sd: Turn 2 vector subclasses into aliases
They don't add any extra functionality, so no need
to subclass std::vector instead of just using it.

Also address

    /home/michi/development/git/libreoffice/sd/source/ui/framework/factories/BasicViewFactory.cxx:71:28: error: if zero-initialization of 'ViewShellContainer' (aka 'vector<std::shared_ptr<ViewDescriptor>>') is intentional here, better make that more explicit (e.g., assigning to members, default constructor, default member initializers, std::memset) [loplugin:subtlezeroinit]
       71 |     : mpViewShellContainer(new ViewShellContainer()),
          |                            ^~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

Change-Id: Ia58b669e61d1350b1742dbc8e86339fb64f22c03
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/185379
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>
Tested-by: Jenkins