Fix build: move CrashReporter code to vcl/source/window/builder.cxx
This problem appeared after commit 1a1bf2b78d689a570cc71b7bcb3e0100947a2fb1
(tdf#130857 VclBuilder: Extract helper to start parsing UI file, 2024-09-26):

[LNK] Library/libvclplug_qt5lo.so
/home/mk/core/include/vcl/widgetbuilder.hxx:55: error: undefined reference to 'CrashReporter::addKeyValue(rtl::OUString const&, rtl::OUString const&, CrashReporter::tAddKeyHandling)'
collect2: error: ld returned 1 exit status
make[1]: *** [/home/mk/core/vcl/Library_vclplug_qt5.mk:20: /home/mk/build/instdir/program/libvclplug_qt5lo.so] Error 1

Change-Id: I212aa3cbc381770de8fec07ea6454ab209edefc6
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/173977
Tested-by: Jenkins
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>