UBSan CppunitTest_sw_writerfilter_misc needs the SwXTextFieldMasters now
...presumably since 85b2d335a4ec0af84ca4801ba04f45f0ed5a7c10 "use more concrete
UNO type in writerfilter",

> DynamicLibraryManagerException: "Failed to load dynamic library: /home/tdf/lode/jenkins/workspace/lo_ubsan/workdir/LinkTarget/CppunitTest/libtest_sw_writerfilter_misc.so
> /home/tdf/lode/jenkins/workspace/lo_ubsan/instdir/program/libsw_writerfilterlo.so: undefined symbol: _ZTI19SwXTextFieldMasters"

(<https://ci.libreoffice.org//job/lo_ubsan/3266/>)

Change-Id: I312cad93ec81546bbd7c67ec725815a07378b462
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/171617
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>