tdf#130857 sc: Connect signal handlers after inserting/removing dummy entry
Only connect signal handlers after having determined
and set the preferred width of the combobox based
on a dummy entry that is inserted, then removed again
after determining the width required for its text.

This prevents a crash seen with the qt6 vcl plugin
and native Qt widgets (for which support will be declared
in an upcoming commit) when starting the "Standard Filter"
dialog due to the removal of the dummy
entry emitting the signal that the currently active
entry has changed, and the handler trying to access
a vector element that is only inserted later in
ScFilterDlg::Init.

    /usr/lib/gcc/x86_64-linux-gnu/15/../../../../include/c++/15/debug/vector:523:
    In function:
        reference std::vector<weld::ComboBox *>::operator[](size_type) [_Tp =
        weld::ComboBox *, _Allocator = std::allocator<weld::ComboBox *>]

    Error: attempt to subscript container with out-of-bounds index 0, but
    container only holds 0 elements.

    Objects involved in the operation:
        sequence "this" @ 0x562b299ef400 {
          type = std::debug::vector<weld::ComboBox*, std::allocator<weld::ComboBox*> >;
        }

An alternative solution could be to block signals
when calling weld::ComboBox::clear.

The dialog can be triggered like this:

* start Calc
* "Data" -> "More Filters" -> "Standard Filter..."

Backtrace:

    1 __pthread_kill_implementation pthread_kill.c 44 0x7f19f2aa11dc
    2 __pthread_kill_internal pthread_kill.c 89 0x7f19f2aa129f
    3 __GI_raise raise.c 26 0x7f19f2a4a842
    4 __GI_abort abort.c 77 0x7f19f2a324b2
    5 __gnu_debug::_Error_formatter::_M_error() const gdb 0x7f19f26acc81
    6 std::vector<weld::ComboBox *>::operator[] vector 523 0x7f199b297823
    7 ScFilterDlg::UpdateValueList filtdlg.cxx 487 0x7f199b28ff99
    8 ScFilterDlg::LbSelectHdl filtdlg.cxx 967 0x7f199b2946a2
    9 ScFilterDlg::LinkStubLbSelectHdl filtdlg.cxx 853 0x7f199b28f71d
    10 Link<weld::ComboBox&, void>::Call link.hxx 105 0x7f19dfc86191
    11 weld::ComboBox::signal_changed ComboBox.hxx 71 0x7f19dfc85da8
    12 QtInstanceComboBox::signalChanged QtInstanceComboBox.cxx 431 0x7f19dfc7a26d
    13 QtPrivate::FunctorCall<std::integer_sequence<unsigned long>, QtPrivate::List<>, void, void (QtInstanceComboBox:: *)()>::call(void (QtInstanceComboBox:: *)(), QtInstanceComboBox *, void * *)::{lambda()#1}::operator()() const qobjectdefs_impl.h 128 0x7f19dfc865b1
    14 QtPrivate::FunctorCallBase::call_internal<void, QtPrivate::FunctorCall<std::integer_sequence<unsigned long>, QtPrivate::List<>, void, void (QtInstanceComboBox:: *)()>::call(void (QtInstanceComboBox:: *)(), QtInstanceComboBox *, void * *)::{lambda()#1}>(void * *, QtPrivate::FunctorCall<std::integer_sequence<unsigned long>, QtPrivate::List<>, void, void (QtInstanceComboBox:: *)()>::call(void (QtInstanceComboBox:: *)(), QtInstanceComboBox *, void * *)::{lambda()#1}&&) qobjectdefs_impl.h 66 0x7f19dfc864e9
    15 QtPrivate::FunctorCall<std::integer_sequence<unsigned long>, QtPrivate::List<>, void, void (QtInstanceComboBox:: *)()>::call(void (QtInstanceComboBox:: *)(), QtInstanceComboBox *, void * *) qobjectdefs_impl.h 127 0x7f19dfc8641b
    16 QtPrivate::FunctionPointer<void (QtInstanceComboBox:: *)()>::call<QtPrivate::List<>, void>(void (QtInstanceComboBox:: *)(), QtInstanceComboBox *, void * *) qobjectdefs_impl.h 175 0x7f19dfc8639d
    17 QtPrivate::QCallableObject<void (QtInstanceComboBox:: *)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase *, QObject *, void * *, bool *) qobjectdefs_impl.h 546 0x7f19dfc862c6
    18 QtPrivate::QSlotObjectBase::call qobjectdefs_impl.h 462 0x7f19deaefbf2
    19 doActivate<false> qobject.cpp 4406 0x7f19ded261ac
    20 QMetaObject::activate qobject.cpp 4467 0x7f19ded1c153
    21 QMetaObject::activate<void, QString> qobjectdefs.h 320 0x7f19dcc8840b
    22 QComboBox::currentTextChanged moc_qcombobox.cpp 374 0x7f19dce468b1
    23 QComboBoxPrivate::updateCurrentText qcombobox.cpp 3203 0x7f19dce43d1d
    24 QComboBoxPrivate::emitCurrentIndexChanged qcombobox.cpp 1696 0x7f19dce43ffe
    25 QComboBoxPrivate::setCurrentIndex qcombobox.cpp 2473 0x7f19dce3f05b
    26 QComboBoxPrivate::rowsRemoved qcombobox.cpp 1427 0x7f19dce441ef
    27 QtPrivate::FunctorCall<std::integer_sequence<unsigned long, 0ul, 1ul, 2ul>, QtPrivate::List<QModelIndex const&, int, int>, void, void (QComboBoxPrivate:: *)(QModelIndex const&, int, int)>::call(void (QComboBoxPrivate:: *)(QModelIndex const&, int, int), QComboBoxPrivate *, void * *)::{lambda()#1}::operator()() const qobjectdefs_impl.h 128 0x7f19dce5dca2
    28 QtPrivate::FunctorCallBase::call_internal<void, QtPrivate::FunctorCall<std::integer_sequence<unsigned long, 0ul, 1ul, 2ul>, QtPrivate::List<QModelIndex const&, int, int>, void, void (QComboBoxPrivate:: *)(QModelIndex const&, int, int)>::call(void (QComboBoxPrivate:: *)(QModelIndex const&, int, int), QComboBoxPrivate *, void * *)::{lambda()#1}>(void * *, QtPrivate::FunctorCall<std::integer_sequence<unsigned long, 0ul, 1ul, 2ul>, QtPrivate::List<QModelIndex const&, int, int>, void, void (QComboBoxPrivate:: *)(QModelIndex const&, int, int)>::call(void (QComboBoxPrivate:: *)(QModelIndex const&, int, int), QComboBoxPrivate *, void * *)::{lambda()#1}&&) qobjectdefs_impl.h 66 0x7f19dce5dbfd
    29 QtPrivate::FunctorCall<std::integer_sequence<unsigned long, 0ul, 1ul, 2ul>, QtPrivate::List<QModelIndex const&, int, int>, void, void (QComboBoxPrivate:: *)(QModelIndex const&, int, int)>::call qobjectdefs_impl.h 127 0x7f19dce5dbb7
    30 QtPrivate::FunctionPointer<void (QComboBoxPrivate:: *)(QModelIndex const&, int, int)>::call<QtPrivate::List<QModelIndex const&, int, int>, void> qobjectdefs_impl.h 175 0x7f19dce5db21
    31 QtPrivate::QPrivateSlotObject<void (QComboBoxPrivate:: *)(QModelIndex const&, int, int), QtPrivate::List<QModelIndex const&, int, int>, void>::impl qobject_p.h 273 0x7f19dce5da50
    32 QtPrivate::QSlotObjectBase::call qobjectdefs_impl.h 462 0x7f19deaefbf2
    33 doActivate<false> qobject.cpp 4406 0x7f19ded261ac
    34 QMetaObject::activate qobject.cpp 4467 0x7f19ded1c153
    35 QMetaObject::activate<void, QModelIndex, int, int, QAbstractItemModel::QPrivateSignal> qobjectdefs.h 320 0x7f19df1cfbd5
    36 QAbstractItemModel::rowsRemoved moc_qabstractitemmodel.cpp 700 0x7f19df1c403a
    37 QAbstractItemModel::endRemoveRows qabstractitemmodel.cpp 3036 0x7f19df1c3fb6
    38 QSortFilterProxyModelPrivate::remove_proxy_interval qsortfilterproxymodel.cpp 822 0x7f19df26f570
    39 QSortFilterProxyModelPrivate::remove_source_items qsortfilterproxymodel.cpp 789 0x7f19df26f3e9
    40 QSortFilterProxyModelPrivate::source_items_about_to_be_removed qsortfilterproxymodel.cpp 1092 0x7f19df2712f0
    41 QSortFilterProxyModelPrivate::_q_sourceRowsAboutToBeRemoved qsortfilterproxymodel.cpp 1817 0x7f19df274721
    42 QtPrivate::FunctorCall<std::integer_sequence<unsigned long, 0ul, 1ul, 2ul>, QtPrivate::List<QModelIndex const&, int, int>, void, void (QSortFilterProxyModelPrivate:: *)(QModelIndex const&, int, int)>::call(void (QSortFilterProxyModelPrivate:: *)(QModelIndex const&, int, int), QSortFilterProxyModelPrivate *, void * *)::{lambda()#1}::operator()() const qobjectdefs_impl.h 128 0x7f19df2b9822
    43 QtPrivate::FunctorCallBase::call_internal<void, QtPrivate::FunctorCall<std::integer_sequence<unsigned long, 0ul, 1ul, 2ul>, QtPrivate::List<QModelIndex const&, int, int>, void, void (QSortFilterProxyModelPrivate:: *)(QModelIndex const&, int, int)>::call(void (QSortFilterProxyModelPrivate:: *)(QModelIndex const&, int, int), QSortFilterProxyModelPrivate *, void * *)::{lambda()#1}>(void * *, QtPrivate::FunctorCall<std::integer_sequence<unsigned long, 0ul, 1ul, 2ul>, QtPrivate::List<QModelIndex const&, int, int>, void, void (QSortFilterProxyModelPrivate:: *)(QModelIndex const&, int, int)>::call(void (QSortFilterProxyModelPrivate:: *)(QModelIndex const&, int, int), QSortFilterProxyModelPrivate *, void * *)::{lambda()#1}&&) qobjectdefs_impl.h 66 0x7f19df2b977d
    44 QtPrivate::FunctorCall<std::integer_sequence<unsigned long, 0ul, 1ul, 2ul>, QtPrivate::List<QModelIndex const&, int, int>, void, void (QSortFilterProxyModelPrivate:: *)(QModelIndex const&, int, int)>::call qobjectdefs_impl.h 127 0x7f19df2b9737
    45 QtPrivate::FunctionPointer<void (QSortFilterProxyModelPrivate:: *)(QModelIndex const&, int, int)>::call<QtPrivate::List<QModelIndex const&, int, int>, void> qobjectdefs_impl.h 175 0x7f19df2b96a1
    46 QtPrivate::QPrivateSlotObject<void (QSortFilterProxyModelPrivate:: *)(QModelIndex const&, int, int), QtPrivate::List<QModelIndex const&, int, int>, void>::impl qobject_p.h 273 0x7f19df2b95d0
    47 QtPrivate::QSlotObjectBase::call qobjectdefs_impl.h 462 0x7f19deaefbf2
    48 doActivate<false> qobject.cpp 4406 0x7f19ded261ac
    49 QMetaObject::activate qobject.cpp 4467 0x7f19ded1c153
    50 QMetaObject::activate<void, QModelIndex, int, int, QAbstractItemModel::QPrivateSignal> qobjectdefs.h 320 0x7f19df1cfbd5
    51 QAbstractItemModel::rowsAboutToBeRemoved moc_qabstractitemmodel.cpp 694 0x7f19df1c3f0a
    52 QAbstractItemModel::beginRemoveRows qabstractitemmodel.cpp 3019 0x7f19df1c3e7b
    53 QStandardItemModelPrivate::rowsAboutToBeRemoved qstandarditemmodel.cpp 602 0x7f19de080845
    54 QStandardItem::removeRows qstandarditemmodel.cpp 1762 0x7f19de081d5e
    55 QStandardItemModel::removeRows qstandarditemmodel.cpp 3002 0x7f19de084dbb
    56 QSortFilterProxyModel::removeRows qsortfilterproxymodel.cpp 2491 0x7f19df277853
    57 QComboBox::clear qcombobox.cpp 3215 0x7f19dce49a6c
    58 QtInstanceComboBox::clear()::$_0::operator()() const QtInstanceComboBox.cxx 103 0x7f19dfc7fcbc
    59 std::__invoke_impl<void, QtInstanceComboBox::clear()::$_0&>(std::__invoke_other, QtInstanceComboBox::clear()::$_0&) invoke.h 63 0x7f19dfc7fc95
    60 std::__invoke_r<void, QtInstanceComboBox::clear()::$_0&>(QtInstanceComboBox::clear()::$_0&) invoke.h 113 0x7f19dfc7fc45
    61 std::_Function_handler<void(), QtInstanceComboBox::clear()::$_0>::_M_invoke std_function.h 292 0x7f19dfc7fb6d
    62 std::function<void()>::operator() std_function.h 593 0x7f19dfc326fe
    63 QtInstance::RunInMainThread QtInstance.cxx 216 0x7f19dfc29e8f
    64 QtInstanceComboBox::clear QtInstanceComboBox.cxx 103 0x7f19dfc7b1fb
    65 ScFilterDlg::Init filtdlg.cxx 189 0x7f199b28d307
    66 ScFilterDlg::ScFilterDlg filtdlg.cxx 124 0x7f199b28c7ff
    67 std::_Construct<ScFilterDlg, SfxBindings *, SfxChildWindow *&, weld::Window *&, ScViewData&, SfxItemSet&> stl_construct.h 133 0x7f199bbaa206
    68 std::allocator_traits<std::allocator<void>>::construct<ScFilterDlg, SfxBindings *, SfxChildWindow *&, weld::Window *&, ScViewData&, SfxItemSet&> alloc_traits.h 805 0x7f199bba9e2a
    69 std::_Sp_counted_ptr_inplace<ScFilterDlg, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<SfxBindings *, SfxChildWindow *&, weld::Window *&, ScViewData&, SfxItemSet&> shared_ptr_base.h 606 0x7f199bba9e2a
    70 std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<ScFilterDlg, std::allocator<void>, SfxBindings *, SfxChildWindow *&, weld::Window *&, ScViewData&, SfxItemSet&> shared_ptr_base.h 970 0x7f199bba9b8f
    71 std::__shared_ptr<ScFilterDlg, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<void>, SfxBindings *, SfxChildWindow *&, weld::Window *&, ScViewData&, SfxItemSet&> shared_ptr_base.h 1719 0x7f199bba9ab6
    72 std::shared_ptr<ScFilterDlg>::shared_ptr<std::allocator<void>, SfxBindings *, SfxChildWindow *&, weld::Window *&, ScViewData&, SfxItemSet&> shared_ptr.h 463 0x7f199bba9a20
    73 std::make_shared<ScFilterDlg, SfxBindings *, SfxChildWindow *&, weld::Window *&, ScViewData&, SfxItemSet&> shared_ptr.h 1007 0x7f199bb97a5f
    74 ScTabViewShell::CreateRefDialogController tabvwshc.cxx 376 0x7f199bb93b0c
    75 ScFilterDlgWrapper::ScFilterDlgWrapper reffact.cxx 103 0x7f199badd335
    76 std::make_unique<ScFilterDlgWrapper, vcl::Window *&, unsigned short&, SfxBindings&, SfxChildWinInfo&> unique_ptr.h 1103 0x7f199bae03b6
    77 ScFilterDlgWrapper::CreateImpl reffact.cxx 41 0x7f199bada1c4
    78 SfxChildWindow::CreateChildWindow childwin.cxx 244 0x7f19ee8c1a32
    79 SfxWorkWindow::CreateChildWin_Impl workwin.cxx 1367 0x7f19ee95abea
    80 SfxWorkWindow::ToggleChildWindow_Impl workwin.cxx 1850 0x7f19ee95cf83
    81 SfxWorkWindow::SetChildWindow_Impl workwin.cxx 1948 0x7f19ee95d7eb
    82 SfxViewFrame::SetChildWindow viewfrm.cxx 3780 0x7f19ef049957
    83 ScModule::SetRefDialog scmod.cxx 1610 0x7f199b18ea81
    84 ScCellShell::ExecuteDB cellsh2.cxx 657 0x7f199b9668ab
    85 SfxStubScCellShellExecuteDB scslots.hxx 7929 0x7f199b93bd45
    86 SfxDispatcher::Call_Impl dispatch.cxx 258 0x7f19ee9c5b2e
    87 SfxDispatcher::Execute_ dispatch.cxx 757 0x7f19ee9ca1f6
    88 SfxBindings::Execute_Impl bindings.cxx 1047 0x7f19ee9b20ae
    89 SfxDispatchController_Impl::dispatch unoctitm.cxx 737 0x7f19eea8e2bd
    90 SfxOfficeDispatch::dispatch unoctitm.cxx 256 0x7f19eea8cd74
    91 framework::(anonymous namespace)::AsyncMenuExecute menubarmanager.cxx 793 0x7f19eff551a4
    92 Link<void *, void>::Call link.hxx 105 0x7f19e8caaf41
    93 ImplHandleUserEvent winproc.cxx 2314 0x7f19e8ca6881
    94 ImplWindowFrameProc winproc.cxx 2869 0x7f19e8ca37b5
    95 SalFrame::CallCallback salframe.hxx 309 0x7f19dfc0b00c
    96 QtInstance::ProcessEvent QtInstance.cxx 564 0x7f19dfc2ccef
    97 SalUserEventList::DispatchUserEvents(bool)::$_0::operator()() const salusereventlist.cxx 119 0x7f19e927d4ed
    98 SalUserEventList::DispatchUserEvents salusereventlist.cxx 120 0x7f19e927d3c4
    99 QtInstance::ImplYield QtInstance.cxx 458 0x7f19dfc29651
    100 QtInstance::DoYield QtInstance.cxx 480 0x7f19dfc2c8b1
    101 InnerYield svapp.cxx 389 0x7f19e9346746
    102 Application::Yield svapp.cxx 502 0x7f19e9345fcf
    103 Application::Execute svapp.cxx 364 0x7f19e9345db0
    104 desktop::Desktop::Main app.cxx 1679 0x7f19f2d1f0f5
    105 ImplSVMainRun svmain.cxx 234 0x7f19e936f92c
    106 SalInstance::SVMainRun salinst.hxx 108 0x7f19dfc34dd1
    107 ImplSVMain svmain.cxx 221 0x7f19e936ee52
    108 SVMain svmain.cxx 252 0x7f19e93709e9
    109 soffice_main sofficemain.cxx 122 0x7f19f2d9916a
    110 sal_main main.c 51 0x562aefa2f9fd
    111 main main.c 49 0x562aefa2f9d7

Change-Id: I05b44d370d08c075314c2cce4011a1efad730dab
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/208561
Tested-by: Jenkins
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>