fix warning C6011: Dereferencing NULL pointer 'this->pView->GetSfxViewShell()'
C:/cygwin/home/tdf/lode/jenkins/workspace/lo_tb_master_win_analyze/sc/source/ui/drawfunc/fudraw.cxx(146): error C2220: the following warning is treated as an error
C:\cygwin\home\tdf\lode\jenkins\workspace\lo_tb_master_win_analyze\sc\source\ui\drawfunc\fudraw.cxx(139) : warning C6011: Dereferencing NULL pointer 'this->pView->GetSfxViewShell()'. : Lines: 139
make[1]: *** [C:/cygwin/home/tdf/lode/jenkins/workspace/lo_tb_master_win_analyze/solenv/gbuild/LinkTarget.mk:335: C:/cygwin/home/tdf/lode/jenkins/workspace/lo_tb_master_win_analyze/workdir/CxxObject/sc/source/ui/drawfunc/fudraw.o] Error 2
make[1]: *** Waiting for unfinished jobs....

after
commit 34e6b6a7c1d3f6f7eaabe168e993b05049e7f0a4
Author: Irgaliev Amin <irgaliev01@mail.ru>
Date:   Wed Aug 13 20:22:21 2025 +0400

    tdf#79356 - Adding connector support for Calc.

Change-Id: I40e7461953164e69e8e77bab01f796f1637b1ec3
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/190079
Tested-by: Jenkins
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>