filter: fix -Werror=sign-compare
Seen with gcc12:
filter/source/config/cache/filtercache.cxx: In constructor ‘filter::config::FilterCache::FilterCache()’:
filter/source/config/cache/filtercache.cxx:76:14: error: comparison of integer expressions of different signedness: ‘int’ and ‘std::size_t’ {aka ‘long unsigned int’} [-Werror=sign-compare]
   76 |     assert(i == std::size(sStandardProps));
      |            ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
filter/source/config/cache/filtercache.cxx:97:14: error: comparison of integer expressions of different signedness: ‘int’ and ‘std::size_t’ {aka ‘long unsigned int’} [-Werror=sign-compare]
   97 |     assert(i == std::size(sTypeProps));

after
commit 48d9138b7460748faf1b21028bd11dc951d65e97
Author: Liam Connors <liam.m.connors@gmail.com>
Date:   Sun Mar 8 18:03:18 2026 -0700

    tdf#147021 replace SAL_N_ELEMENTS with std::size

Change-Id: Iee239626110ff1f50cc9abeb693bc368e1d7607d
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/201500
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>
Tested-by: Jenkins