qt: Include QtTools header in QtMenu.cxx
Required for `toImage` and more helper functions.

Fixes this build failure seen on Windows with
Hossein's WIP Gerrit change [1]:

    C:\Users\mwegh\development\git\libreoffice\vcl\qt6\../qt5/QtMenu.cxx(611): error C3861: 'toQImage': identifier not found

[1] https://gerrit.libreoffice.org/c/core/+/199615

Change-Id: I37b1f55a199e411c0b2dfbfbfe465b24c25f3c85
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/200195
Tested-by: Jenkins
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>