android: Drop non-working fullUI build variant
That build variant whose build could be triggered
e.g. by running

    ./gradlew assembleFullUIRelease

from `android/source` would fail to build for
a long time already, like this:

  /home/michi/development/git/libreoffice-WORKTREE-android/android/source/src/java/org/libreoffice/ui/LibreOfficeUIActivity.java:189: error: cannot find symbol
          final boolean bEditingEnabled = BuildConfig.ALLOW_EDITING && preferences.getBoolean(LibreOfficeMainActivity.ENABLE_EXPERIMENTAL_PREFS_KEY, false);
                                                     ^
    symbol:   variable ALLOW_EDITING
    location: class BuildConfig

In addition, it would be the default variant
used by Android Studio, so in order to get
a working build, it was always necessary to
explicitly switch to another variant first
(using "Build" -> "Select build variant").

Drop it altogether, since it's unused.
(It would include all of the .ui files
in the APK while the other build variants
explicitly specify what files to include.)

Change-Id: I0a6096ec69897eb57f41c512e88a4c1a848480ee
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/187623
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>
Tested-by: Jenkins