tdf#104833 update check: Fix --enable-mergelibs build
Fix build for the case where both autogen options
--enable-mergelibs and --enable-online-update are used.

After

    commit 96ba07a515e1c346bdfa2cd91e87fe7afdf56e91
    Author: Michael Weghorn <m.weghorn@posteo.de>
    Date:   Wed Sep 17 11:32:25 2025 +0200

        tdf#104833 update check: Use ProgressBar methods directly

, this was seen failing as follows in the daily build [1]:

    /home/tdf/lode/jenkins/workspace/lo_gerrit/tb/src_master/extensions/source/update/check/updatehdl.cxx:244: undefined reference to `ProgressBar::SetValue(unsigned short)'
    /opt/rh/gcc-toolset-12/root/usr/libexec/gcc/x86_64-redhat-linux/12/ld: /tmp/cchzxrtC.ltrans2.ltrans.o: in function `UpdateHandler::updateState(UpdateState)':
    /home/tdf/lode/jenkins/workspace/lo_gerrit/tb/src_master/extensions/source/update/check/updatehdl.cxx:564: undefined reference to `ProgressBar::SetValue(unsigned short)'
    /opt/rh/gcc-toolset-12/root/usr/libexec/gcc/x86_64-redhat-linux/12/ld: /tmp/cchzxrtC.ltrans2.ltrans.o: in function `UpdateHandler::createDialog()':
    /home/tdf/lode/jenkins/workspace/lo_gerrit/tb/src_master/extensions/source/update/check/updatehdl.cxx:1241: undefined reference to `typeinfo for ProgressBar'
    /opt/rh/gcc-toolset-12/root/usr/libexec/gcc/x86_64-redhat-linux/12/ld: /home/tdf/lode/jenkins/workspace/lo_gerrit/tb/src_master/extensions/source/update/check/updatehdl.cxx:1243: undefined reference to `typeinfo for FixedText'
    /opt/rh/gcc-toolset-12/root/usr/libexec/gcc/x86_64-redhat-linux/12/ld: /home/tdf/lode/jenkins/workspace/lo_gerrit/tb/src_master/extensions/source/update/check/updatehdl.cxx:1245: undefined reference to `FixedText::set_mnemonic_widget(vcl::Window*)'
    /opt/rh/gcc-toolset-12/root/usr/libexec/gcc/x86_64-redhat-linux/12/ld: /home/tdf/lode/jenkins/workspace/lo_gerrit/tb/src_master/extensions/source/update/check/updatehdl.cxx:1247: undefined reference to `typeinfo for FixedText'
    /opt/rh/gcc-toolset-12/root/usr/libexec/gcc/x86_64-redhat-linux/12/ld: /home/tdf/lode/jenkins/workspace/lo_gerrit/tb/src_master/extensions/source/update/check/updatehdl.cxx:1249: undefined reference to `FixedText::set_mnemonic_widget(vcl::Window*)'
    collect2: error: ld returned 1 exit status

[1] https://ci.libreoffice.org/job/lo_daily_tb_linux/1415/consoleFull#-117369509718ea88b4-cafc-4624-83a7-468a3ab5c53a

Change-Id: I53b6584e25d89a52aed0c14161891c790dff3315
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/191200
Tested-by: Jenkins
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>