Fix UBSan build's RTTI needs
...after 3ba92b5f1eaf7d4447a0943ea260db515ca799dc "hide more symbols" had caused
CppunitTest_vcl_text to fail with

> DynamicLibraryManagerException: "Failed to load dynamic library: /home/tdf/lode/jenkins/workspace/lo_ubsan/workdir/LinkTarget/CppunitTest/libtest_vcl_text.so
> /home/tdf/lode/jenkins/workspace/lo_ubsan/workdir/LinkTarget/CppunitTest/libtest_vcl_text.so: undefined symbol: _ZTIN3vcl8unotools15VclCanvasBitmapE"
> Path (length: 252) is '/home/tdf/lode/opt/bin:/etc/alternatives/java_sdk_11/bin:/opt/rh/gcc-toolset-12/root/usr/bin:/home/tdf/.local/bin:/home/tdf/bin:/usr/share/Modules/bin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/etc/alternatives/java_sdk_17/bin'

(<https://ci.libreoffice.org/job/lo_ubsan/3080/>)

Change-Id: Ib0a82e185a8600955704f8026238b511d46acc56
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/163685
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>