a11y: Drop SAL_LOPLUGIN_ANNOTATE("crosscast")
Added in:

    commit d66a97d5622bfc7c8d68452eb5a3c2378b0b1820
    Date:   Thu Jan 12 08:29:24 2023 +0100

        loplugin:crosscast (clang-cl)

        > winaccessibility/source/service/AccTopWindowListener.cxx(47,36): error: suspicious dynamic cross cast from 'css::accessibility::XAccessible *' to 'VCLXAccessibleComponent *' [loplugin:crosscast]
        >     else if (auto pvclxcomponent = dynamic_cast<VCLXAccessibleComponent*>(pAccessible))
        >                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

        Change-Id: Iee7585dd2fa0d92af3be6b89d7d08326de3d1e7b
        Reviewed-on: https://gerrit.libreoffice.org/c/core/+/145380
        Tested-by: Jenkins
        Reviewed-by: Stephan Bergmann <sbergman@redhat.com>

AccTopWindowListener::HandleWindowOpened no longer does
that crosscast now, see

    Change-Id: Ic96d2c95128af144c7769aac40707299b1c80f8c
    Author: Michael Weghorn <m.weghorn@posteo.de>
    Date:   Thu Dec 5 14:07:52 2024 +0000

        tdf#164093 tdf#157001 wina11y: Use vcl::Window's actual XAccessible

Change-Id: Ifca76a5d519099f9cbe06f8bde606e01871363fc
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/177891
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>
Tested-by: Jenkins