sc: fix warning C6011: Dereferencing NULL pointer 'this->GetDocument()'
C:/cygwin/home/tdf/lode/jenkins/workspace/lo_tb_master_win_analyze/sc/source/filter/xml/xmlfonte.cxx(149): error C2220: the following warning is treated as an error
C:\cygwin\home\tdf\lode\jenkins\workspace\lo_tb_master_win_analyze\sc\source\filter\xml\xmlfonte.cxx(149) : warning C6011: Dereferencing NULL pointer 'this->GetDocument()'. : Lines: 149
C:\cygwin\home\tdf\lode\jenkins\workspace\lo_tb_master_win_analyze\sc\source\filter\xml\xmlfonte.cxx(150) : warning C6011: Dereferencing NULL pointer 'this->GetDocument()'. : Lines: 150
C:\cygwin\home\tdf\lode\jenkins\workspace\lo_tb_master_win_analyze\sc\source\filter\xml\xmlfonte.cxx(151) : warning C6011: Dereferencing NULL pointer 'this->GetDocument()'. : Lines: 151
C:\cygwin\home\tdf\lode\jenkins\workspace\lo_tb_master_win_analyze\sc\source\filter\xml\xmlfonte.cxx(152) : warning C6011: Dereferencing NULL pointer 'this->GetDocument()'. : Lines: 152
C:\cygwin\home\tdf\lode\jenkins\workspace\lo_tb_master_win_analyze\sc\source\filter\xml\xmlfonte.cxx(153) : warning C6011: Dereferencing NULL pointer 'this->GetDocument()'. : Lines: 153
make[1]: *** [C:/cygwin/home/tdf/lode/jenkins/workspace/lo_tb_master_win_analyze/solenv/gbuild/LinkTarget.mk:338: C:/cygwin/home/tdf/lode/jenkins/workspace/lo_tb_master_win_analyze/workdir/CxxObject/sc/source/filter/xml/xmlfonte.o] Error 2
make[1]: *** Waiting for unfinished jobs....

after
commit e61a179b4ff8ce2072c3c0780628eb38c7a43529
Author: Mike Kaganski <mike.kaganski@collabora.com>
Date:   Fri May 23 12:14:27 2025 +0500

    tdf#166627: embed fonts everywhere we emit font data

Change-Id: Ic81b8193dec7fc9f8d2e3468ea09f9d24c4d3be1
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/185721
Reviewed-by: Mike Kaganski <mike.kaganski@collabora.com>
Tested-by: Jenkins