sc: fix warning C6011: Dereferencing NULL pointer 'pFontAttr'
E:/jenkins/workspace/lo_tb_master_win_analyze/sc/source/core/data/patattr.cxx(770): error C2220: the following warning is treated as an error
E:\jenkins\workspace\lo_tb_master_win_analyze\sc\source\core\data\patattr.cxx(720) : warning C6011: Dereferencing NULL pointer 'pFontAttr'. : Lines: 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 625, 626, 627, 628, 629, 630, 632, 694, 696, 697, 699, 700, 702, 703, 704, 705, 706, 707, 708, 709, 710, 712, 714, 720

Since
commit 365cdb242f2812292b5b2fec854b25f389d6787f
Author: Balazs Varga <balazs.varga@collabora.com>
Date:   Wed Oct 8 08:16:38 2025 +0200

    Support Font styles in Table styles

Change-Id: I9050f3059d3aab958b55b0a4b76882af7d4a96f8
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/198828
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>
Tested-by: Jenkins