sc: Add missing weld includes in filtdlg.hxx
This addresses various errors like

    filtdlg.hxx:89:23: No member named 'ComboBox' in namespace 'weld'

shown in Qt Creator.
(They probably didn't result in build failures
due to anything including that header already
including the necessary includes before this one,
but that shouldn't be necessary.)

Change-Id: Ia92da0a4b2a29435fc2daf907d509cf684967b7e
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/208566
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>
Tested-by: Jenkins