ui-rules-enforcer: Check that menu item has an id
See

    commit 616a3177da38d3db342593149ab2a9a94799cfe8
    Author: Michael Weghorn <m.weghorn@posteo.de>
    Date:   Tue Jun 3 12:01:12 2025 +0200

        basctl: Set menu item ID to fix gtk4 crash

Prior to this commit, the newly introduced check
would have failed with

    $ python3 ./bin/ui-rules-enforcer.py basctl/uiconfig/basicide/ui/sortmenu.ui
    Traceback (most recent call last):
      File "/home/michi/development/git/libreoffice/./bin/ui-rules-enforcer.py", line 647, in <module>
        enforce_menuitem_id(root)
        ~~~~~~~~~~~~~~~~~~~^^^^^^
      File "/home/michi/development/git/libreoffice/./bin/ui-rules-enforcer.py", line 611, in enforce_menuitem_id
        enforce_menuitem_id(child)
        ~~~~~~~~~~~~~~~~~~~^^^^^^^
      File "/home/michi/development/git/libreoffice/./bin/ui-rules-enforcer.py", line 611, in enforce_menuitem_id
        enforce_menuitem_id(child)
        ~~~~~~~~~~~~~~~~~~~^^^^^^^
      File "/home/michi/development/git/libreoffice/./bin/ui-rules-enforcer.py", line 614, in enforce_menuitem_id
        raise Exception(sys.argv[1] + ': menu item does not have an id set' , child.text)
    Exception: ('basctl/uiconfig/basicide/ui/sortmenu.ui: menu item does not have an id set', None)

Change-Id: Ic31b0d08f0f981a89a6a6e27b4efe898f7753d6e
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/186160
Tested-by: Jenkins
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>
Reviewed-by: Noel Grandin <noel.grandin@collabora.co.uk>