libodfgen: fix missing include
OdfGenerator.cxx: In function 'void {anonymous}::appendUnicodeTo(long unsigned int, librevenge::RVNGString&)':
OdfGenerator.cxx:58:9: error: 'uint8_t' was not declared in this scope
   58 |         uint8_t first;
      |         ^~~~~~~
OdfGenerator.cxx:47:1: note: 'uint8_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'

Change-Id: I936a13c2ccd0c5a2e9ddc8cf8118d50087997bf3
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/204759
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>
Reviewed-by: Ilmari Lauhakangas <ilmari.lauhakangas@libreoffice.org>
Tested-by: Jenkins