libreofficekitgtk: Add include for SAL_DLLPUBLIC_EXPORT
`SAL_DLLPUBLIC_EXPORT` is defined in `include/sal/types.h`,
so add a corresponding include in
`include/LibreOfficeKit/LibreOfficeKitGtk.h` before using it.

Without this, Qt Creator's Clang code model would'nt find it,
resulting in errors like

    .../libreofficekit/qa/gtktiledviewer/gtv-lokdocview-signal-handlers.cxx:15: error: In included file: unknown type name 'SAL_DLLPUBLIC_EXPORT'

being shown when editing the file
`libreofficekit/qa/gtktiledviewer/gtv-lokdocview-signal-handlers.cxx`
in Qt Creator.

Change-Id: Iedd3490be9de72b931573b305d283d80b25a4645
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/170749
Tested-by: Jenkins
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>