external/boost: Silence -Werror=unused-but-set-variable=
...(with recent GCC 16 trunk), as seen at

> In file included from workdir/UnpackedTarball/boost/boost/multi_array/concept_checks.hpp:21,
>                  from workdir/UnpackedTarball/boost/boost/multi_array/base.hpp:28,
>                  from workdir/UnpackedTarball/boost/boost/multi_array.hpp:29,
>                  from external/boost/include/boost/multi_array.hpp:30,
>                  from vcl/source/window/layout.cxx:57:
> workdir/UnpackedTarball/boost/boost/concept_check.hpp: In instantiation of ‘boost::InputIterator<TT>::~InputIterator() [with TT = const long unsigned int*]’:
> workdir/UnpackedTarball/boost/boost/concept_check.hpp:502:3:   required from ‘static void boost::concepts::requirement<boost::concepts::failed************ Model::************>::failed() [with Model = boost::InputIteratorConcept<const long unsigned int*>]’
>   502 |   BOOST_concept(InputIterator,(TT))
>       |                 ^~~~~~~~~~~~~
> workdir/UnpackedTarball/boost/boost/concept_check.hpp:50:7:   required from ‘void boost::function_requires(Model*) [with Model = InputIteratorConcept<const long unsigned int*>]’
>    92 |     &::boost::concepts::requirement_<ModelFnPtr>::failed>    \
>       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> workdir/UnpackedTarball/boost/boost/multi_array/multi_array_ref.hpp:391:67:   required from ‘void boost::const_multi_array_ref<T, NumDims, TPtr>::init_multi_array_ref(InputIterator) [with InputIterator = const long unsigned int*; T = {anonymous}::GridEntry; long unsigned int NumDims = 2; TPtr = {anonymous}::GridEntry*]’
>   391 |     boost::function_requires<InputIteratorConcept<InputIterator> >();
>       |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
> workdir/UnpackedTarball/boost/boost/multi_array/multi_array_ref.hpp:340:26:   required from ‘boost::const_multi_array_ref<T, NumDims, TPtr>::const_multi_array_ref(TPtr, const storage_order_type&, const index*, const size_type*) [with T = {anonymous}::GridEntry; long unsigned int NumDims = 2; TPtr = {anonymous}::GridEntry*; storage_order_type = boost::general_storage_order<2>; index = long int; size_type = long unsigned int]’
>   340 |      init_multi_array_ref(extents);
>       |      ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
> workdir/UnpackedTarball/boost/boost/multi_array/multi_array_ref.hpp:616:43:   required from ‘boost::multi_array_ref<T, NumDims>::multi_array_ref(T*, const storage_order_type&, const index*, const size_type*) [with T = {anonymous}::GridEntry; long unsigned int NumDims = 2; storage_order_type = boost::general_storage_order<2>; index = long int; size_type = long unsigned int]’
>   616 |     super_type(base,so,index_bases,extents) { }
>       |                                           ^
> workdir/UnpackedTarball/boost/boost/multi_array.hpp:155:43:   required from ‘boost::multi_array<T, NumDims, Allocator>::multi_array(const Allocator&) [with T = {anonymous}::GridEntry; long unsigned int NumDims = 2; Allocator = std::allocator<{anonymous}::GridEntry>]’
>   155 |     alloc_base(boost::empty_init_t(),alloc) {
>       |                                           ^
> vcl/source/window/layout.cxx:910:16:   required from here
>   910 |     array_type A;
>       |                ^
> workdir/UnpackedTarball/boost/boost/concept_check.hpp:517:12: error: variable ‘j’ set but not used [-Werror=unused-but-set-variable=]
>   517 |         TT j(i);
>       |            ^
> workdir/UnpackedTarball/boost/boost/concept_check.hpp: In instantiation of ‘boost::InputIterator<TT>::~InputIterator() [with TT = long int*]’:
> workdir/UnpackedTarball/boost/boost/concept_check.hpp:502:3:   required from ‘static void boost::concepts::requirement<boost::concepts::failed************ Model::************>::failed() [with Model = boost::InputIteratorConcept<long int*>]’
>   502 |   BOOST_concept(InputIterator,(TT))
>       |                 ^~~~~~~~~~~~~
> workdir/UnpackedTarball/boost/boost/concept_check.hpp:50:7:   required from ‘void boost::function_requires(Model*) [with Model = InputIteratorConcept<long int*>]’
>    92 |     &::boost::concepts::requirement_<ModelFnPtr>::failed>    \
>       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> workdir/UnpackedTarball/boost/boost/multi_array/multi_array_ref.hpp:391:67:   required from ‘void boost::const_multi_array_ref<T, NumDims, TPtr>::init_multi_array_ref(InputIterator) [with InputIterator = long int*; T = {anonymous}::GridEntry; long unsigned int NumDims = 2; TPtr = {anonymous}::GridEntry*]’
>   391 |     boost::function_requires<InputIteratorConcept<InputIterator> >();
>       |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
> workdir/UnpackedTarball/boost/boost/multi_array/multi_array_ref.hpp:344:26:   required from ‘boost::const_multi_array_ref<T, NumDims, TPtr>::const_multi_array_ref(TPtr, const storage_order_type&, const index*, const size_type*) [with T = {anonymous}::GridEntry; long unsigned int NumDims = 2; TPtr = {anonymous}::GridEntry*; storage_order_type = boost::general_storage_order<2>; index = long int; size_type = long unsigned int]’
>   344 |      init_multi_array_ref(extent_list.begin());
>       |      ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
> workdir/UnpackedTarball/boost/boost/multi_array/multi_array_ref.hpp:616:43:   required from ‘boost::multi_array_ref<T, NumDims>::multi_array_ref(T*, const storage_order_type&, const index*, const size_type*) [with T = {anonymous}::GridEntry; long unsigned int NumDims = 2; storage_order_type = boost::general_storage_order<2>; index = long int; size_type = long unsigned int]’
>   616 |     super_type(base,so,index_bases,extents) { }
>       |                                           ^
> workdir/UnpackedTarball/boost/boost/multi_array.hpp:155:43:   required from ‘boost::multi_array<T, NumDims, Allocator>::multi_array(const Allocator&) [with T = {anonymous}::GridEntry; long unsigned int NumDims = 2; Allocator = std::allocator<{anonymous}::GridEntry>]’
>   155 |     alloc_base(boost::empty_init_t(),alloc) {
>       |                                           ^
> vcl/source/window/layout.cxx:910:16:   required from here
>   910 |     array_type A;
>       |                ^
> workdir/UnpackedTarball/boost/boost/concept_check.hpp:517:12: error: variable ‘j’ set but not used [-Werror=unused-but-set-variable=]
>   517 |         TT j(i);
>       |            ^
> cc1plus: all warnings being treated as errors

Change-Id: I5259dfad91e88e4d40c234d969a10b41c18af47f
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/188134
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@collabora.com>