Fix no-pch build
After commit df3483fa74baa0ee73b981df0c106d03dc964a68 "tdf#130857
VclBuilder: Make MenuAndId a template", 2024-11-10

  [CXX] vcl/jsdialog/executor.cxx
  C:\lo\core\include\rtl/ref.hxx(126): error C2027: use of undefined type 'PopupMenu'
  C:\lo\core\include\vcl/builder.hxx(41): note: see declaration of 'PopupMenu'
  C:\lo\core\include\rtl/ref.hxx(126): note: the template instantiation context (the oldest one first) is
  C:\lo\core\include\vcl/toolkit/menubtn.hxx(40): note: see reference to class template instantiation 'VclPtr<PopupMenu>' being compiled
  C:\lo\core\include\vcl/vclptr.hxx(64): note: see reference to class template instantiation 'rtl::Reference<reference_type>' being compiled
  with
  [
  reference_type=PopupMenu
  ]
  C:\lo\core\include\rtl/ref.hxx(123): note: while compiling class template member function 'rtl::Reference<reference_type>::~Reference(void)'
  with
  [
  reference_type=PopupMenu
  ]
  C:\lo\core\include\vcl/vclptr.hxx(217): note: see the first reference to 'rtl::Reference<reference_type>::~Reference' in 'VclPtr<PopupMenu>::~VclPtr'
  with
  [
  reference_type=PopupMenu
  ]

Change-Id: Ifa2f8e55135faf8864a157aeddcf2764f4b2db4b
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/176471
Tested-by: Jenkins
Reviewed-by: Mike Kaganski <mike.kaganski@collabora.com>