update to skia m128
and add a patch to deal with a horrible windows COM header
preprocessor thing, which resulted in:

$ make skia
cd C:/libreoffice/libo-core/external/skia && C:/cygwin64/opt/lo/bin/make -j 8 -rs
[build DEP] LNK:Library/skialo.dll.d
[build CXX] workdir/UnpackedTarball/skia/tools/window/VulkanWindowContext.cpp
[build LOC] top level modules: skia
In file included from C:/libreoffice/libo-core/workdir/UnpackedTarball/skia/tools/window/VulkanWindowContext.cpp:26:
C:/libreoffice/libo-core/workdir/UnpackedTarball/skia\src/gpu/vk/vulkanmemoryallocator/VulkanAMDMemoryAllocator.h(33,69): error:
      invalid parameter name: 'struct' is a keyword
   33 |                                              const VulkanInterface* interface,
      |                                                                     ^
C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\combaseapi.h(168,19): note: expanded from macro
      'interface'
  168 | #define interface __STRUCT__
      |                   ^
C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\combaseapi.h(167,20): note: expanded from macro
      '__STRUCT__'
  167 | #define __STRUCT__ struct
      |                    ^
1 error generated.
make[1]: *** [C:/libreoffice/libo-core/solenv/gbuild/LinkTarget.mk:403: C:/libreoffice/libo-core/workdir/GenCxxObject/UnpackedTarball/skia/tools/window/VulkanWindowContext.o] Error 1
make: *** [Makefile:125: skia] Error 2

Change-Id: I48975bd503098a2c38d794307c7c55f60668232a
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/174760
Tested-by: Jenkins
Reviewed-by: Noel Grandin <noel.grandin@collabora.co.uk>