skia: fix build
/home/julien/lo/libreoffice/workdir/UnpackedTarball/skia/tools/window/VulkanWindowContext.cpp:520:24: error: no member named 'fDestroyDebugUtilsMessengerEXT' in 'skwindow::internal::VulkanWindowContext::Shared'
520 | fGlobalShared->fDestroyDebugUtilsMessengerEXT(fGlobalShared->fInstance, fGlobalShared->fDebugMessenger, nullptr);
| ~~~^
1 error generated.

after
commit 027c65e72e49c1c5dae9d6b5f8151cd2d27442a7
Author: Xisco Fauli <xiscofauli@libreoffice.org>
Date:   Wed Jul 2 14:31:20 2025 +0200

    skia: upgrade to m139

Change-Id: I8413d320733208628b773ea192c9df65c9f03989
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/187374
Tested-by: Jenkins
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>