rust_uno: Define + use valid log areas (loplugin:sallogareas)
As described in include/sal/log.hxx, log areas may not
contain "_", and they need to be defined:

> For all the other macros, the given area argument must be non-null and must
> match the regular expression
>
> @verbatim
>   <area> ::= <segment>("."<segment>)*
> @endverbatim
>
> with
>
> @verbatim
>   <segment> ::= [0-9a-z]+
> @endverbatim
>
> For a list of areas used see @ref sal_log_areas "SAL debug areas". Whenever
> you use a new log area, add it to the file include/sal/log-areas.dox .

This fixes errors like the following ones seen for a --enable-rust-uno
build with clang plugins enabled:

    /home/michi/development/git/libreoffice/rust_uno/uno_bootstrap.cxx:38:14: error: unknown log area 'rust_uno' (check or extend include/sal/log-areas.dox) [loplugin:sallogareas]
       38 |     SAL_INFO("rust_uno", "Initializing UNO component context for Rust binding");
          |              ^

    /home/michi/development/git/libreoffice/codemaker/source/rustmaker/cpproduce.cxx:1011:14: error: unknown log area 'codemaker' (check or extend include/sal/log-areas.dox) [loplugin:sallogareas]
     1011 |     SAL_INFO("codemaker", "Struct member " << member.name << " UNO type: " << unoType);
          |              ^

Change-Id: I4ac11fc343f340488d15607cc7262ca57b6a4850
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/190847
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>
Tested-by: Jenkins