qt: Include QtTools header in QtDragAndDrop.cxx
Required for `toVclDropAction` helper etc.

Fixes these build failures seen on Windows
when experimenting with Hossein's WIP Gerrit change [1]:

    C:\Users\mwegh\development\git\libreoffice\vcl\qt6\../qt5/QtDragAndDrop.cxx(104): error C3861: 'toVclDropAction': identifier not found
    C:\Users\mwegh\development\git\libreoffice\vcl\qt6\../qt5/QtDragAndDrop.cxx(142): error C3861: 'toQtDropActions': identifier not found
    C:\Users\mwegh\development\git\libreoffice\vcl\qt6\../qt5/QtDragAndDrop.cxx(271): error C3861: 'toVclDropActions': identifier not found
    C:\Users\mwegh\development\git\libreoffice\vcl\qt6\../qt5/QtDragAndDrop.cxx(299): error C3861: 'toVclDropActions': identifier not found

[1] https://gerrit.libreoffice.org/c/core/+/199615

Change-Id: Ib1116d7ca82563e23349671de8a05cbb9441c6e1
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/200399
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>
Tested-by: Jenkins