UBSan CppunitTest_sw_writerfilter_misc needs the SwXFootnotes now
...presumably since 5b1bf578fb23ab929602715077138a5362dcb5ce "use more concrete
UNO type in writerfilter",

> DynamicLibraryManagerException: "Failed to load dynamic library: /home/tdf/lode/jenkins/workspace/lo_ubsan/workdir/LinkTarget/CppunitTest/libtest_sw_writerfilter_misc.so
> /home/tdf/lode/jenkins/workspace/lo_ubsan/instdir/program/libsw_writerfilterlo.so: undefined symbol: _ZTI12SwXFootnotes"

(<https://ci.libreoffice.org//job/lo_ubsan/3268/>)

Change-Id: I3be4a8b804cd02d62e38075b3b601360c5c299ad
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/171663
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>