pyuno: Include Python.h first to avoid _POSIX_C_SOURCE redefinitions
As

    commit a545badd656ce00e36945b188f620a67e19fdf55
    Author: Stephan Bergmann <sbergman@redhat.com>
    Date:   Thu Feb 16 18:15:04 2012 +0100

        Work around macro redefinition warning

already did for pyuno/source/module/pyuno_dlopenwrapper.c ,
also include the <Python.h> header first
in more pyuno source files.

Quoting from the Python/C API reference manual about include
files [1]:

> Note: Since Python may define some pre-processor definitions
> which affect the standard headers on some systems, you must
> include Python.h before any standard headers are included.

This avoids build errors like the following otherwise seen
on Debian testing after a glibc update from 2.42-17 to 2.43-3:

    In file included from /home/michi/development/git/libreoffice/pyuno/source/module/pyuno_struct.cxx:28:
    In file included from /home/michi/development/git/libreoffice/pyuno/source/module/pyuno_impl.hxx:26:
    In file included from /home/michi/development/git/libreoffice/workdir/UnpackedTarball/python3/Include/Python.h:14:
    /home/michi/development/git/libreoffice/workdir/UnpackedTarball/python3/pyconfig.h:1985:9: error: '_POSIX_C_SOURCE' macro redefined [-Werror,-Wmacro-redefined]
     1985 | #define _POSIX_C_SOURCE 200809L
          |         ^
    /usr/include/features.h:319:10: note: previous definition is here
      319 | # define _POSIX_C_SOURCE        202405L
          |          ^

[1] https://docs.python.org/3/c-api/intro.html#include-files

Change-Id: I4ae90cfc9b92b559181d3884cdc8d51ee11f922d
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/209871
Tested-by: Jenkins
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>