vcl: Dereferencing NULL pointer 'pData'
After
commit a108fce773d46441e30dcc14abe29751410ae4ed
Author: Michael Weghorn <m.weghorn@posteo.de>
Date:   Fri Jan 17 14:18:30 2025 +0100

    tdf#163186 qt: Show menu item tooltips

C: /cygwin/home/tdf/lode/jenkins/workspace/lo_tb_master_win_analyze/vcl/source/window/menu.cxx(1144): error C2220: the following warning is treated as an error
C: \cygwin\home\tdf\lode\jenkins\workspace\lo_tb_master_win_analyze\vcl\source\window\menu.cxx(1142) : warning C6011: Dereferencing NULL pointer 'pData'. : Lines: 1137, 1139, 1142
Change-Id: I62e8462fcff83817f876489a10bd010e246a1d01
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/180430
Tested-by: Jenkins
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>