external/libetonyek: operation between different enumeration types
> IWORKDiscardContext.cpp:85:30: error: invalid bitwise operation between different enumeration types ('libetonyek::IWORKToken::Namespace' and 'libetonyek::IWORKToken::(unnamed enum at ./IWORKToken.h:25:1)')
>    85 |   case IWORKToken::NS_URI_SF | IWORKToken::bezier :
>       |        ~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~

etc. as reported now with --with-latest-c++ (i.e., in C++26 mode) by Clang 18
trunk since
<https://github.com/llvm/llvm-project/commit/1cbd52f791d3f088246526c0801634edb65cee31>
"[Clang] Implement P2864R2 Remove Deprecated Arithmetic Conversion on
Enumerations (#73105)"

Change-Id: I28bfd1f90df048acea23d9fddd2010bcb537b251
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/160553
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>