Avoid std::stringstream::view()
It breaks our toolchain (Oracle Linux 7, GCC 12)
error: ‘std::stringstream’ {aka ‘class std::basic_stringstream<char>’} has no member named ‘view’

Change-Id: I31bd47c2eb8fd0ef9aa05e3520e8984b77bf16fc
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/196597
Tested-by: Jenkins
Reviewed-by: Andras Timar <andras.timar@collabora.com>