Bump emscripten minimum to 2.0.32 for as_handle
Reading https://github.com/emscripten-core/emscripten/blob/main/ChangeLog.md
val::as_handle() has been added with 2.0.32

It'll allow WASM Jenkins to fail at the configure check step instead in the build with:
/home/tdf/jenkins/workspace/lo_gerrit/tb/src_wasm/static/source/unoembindhelpers/PrimaryBindings.cxx:231:37: error: no member named 'as_handle' in 'emscripten::val'
                = _emval_as(rObject.as_handle(), getTypeId(rUnoType), &destructors);
                            ~~~~~~~ ^
/home/tdf/jenkins/workspace/lo_gerrit/tb/src_wasm/static/source/unoembindhelpers/PrimaryBindings.cxx:240:37: error: no member named 'as_handle' in 'emscripten::val'
                = _emval_as(rObject.as_handle(), getTypeId(rUnoType), &destructors);
                            ~~~~~~~ ^
2 errors generated.

Change-Id: I7531256de46cd4b86b6eac9b1f8d16cad7b46ae2
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/168035
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>