sd: Dereference after null check
C: /cygwin64/home/tdf/jenkins/workspace/gerrit_windows/sd/source/ui/view/drviewsg.cxx(247): error C2220: the following warning is treated as an error
C: \cygwin64\home\tdf\jenkins\workspace\gerrit_windows\sd\source\ui\view\drviewsg.cxx(130) : warning C6011: Dereferencing NULL pointer 'Current()'. : Lines: 106, 109, 110, 112, c:\cygwin64\home\tdf\jenkins\workspace\gerrit_windows\include\comphelper\configuration.hxx:51, c:\cygwin64\home\tdf\jenkins\workspace\gerrit_windows\sd\source\ui\view\drviewsg.cxx:113, 116, 123, 125, 127, 129, 130

Since
commit 9d9c24328cef503f999bf3a5475743e87a3aff5a
Author: Gökay Şatır <gokaysatir@collabora.com>
Date:   Tue Sep 24 13:30:22 2024 +0300

    cool#7406 Inform lokit side about the grid state.

Change-Id: Ic06e765386330cf344380ddf61757298210f921e
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/178655
Tested-by: Jenkins
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>