Instead of warning and failing, just do the right thing
After df83ad933b11e973855d66792c9aff38714f9201 "fix harfbuzz build with
--enable-python=fully-internal on linux", my --enable-python=fully-internal
Linux builds that auto-detect MESON=/usr/bin/meson started to emit a configure
warning

> * WARNING : using internal python with a meson launcher might not work, best to use MESON=/path/to/meson.py in autogen.input

and then fail to build ExternalProject_harfbuzz with

> Traceback (most recent call last):
>   File "/home/sberg/lo/core/instdir/program/python-core-3.11.12/lib/importlib/metadata/__init__.py", line 563, in from_name
>     return next(cls.discover(name=name))
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> StopIteration
>
> During handling of the above exception, another exception occurred:
>
> Traceback (most recent call last):
>   File "/usr/bin/meson", line 33, in <module>
>     sys.exit(load_entry_point('meson==1.7.0', 'console_scripts', 'meson')())
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/bin/meson", line 22, in importlib_load_entry_point
>     for entry_point in distribution(dist_name).entry_points
>                        ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/sberg/lo/core/instdir/program/python-core-3.11.12/lib/importlib/metadata/__init__.py", line 982, in distribution
>     return Distribution.from_name(distribution_name)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/sberg/lo/core/instdir/program/python-core-3.11.12/lib/importlib/metadata/__init__.py", line 565, in from_name
>     raise PackageNotFoundError(name)
> importlib.metadata.PackageNotFoundError: No package metadata was found for meson

So better add back the idea from 736998ccef0bacdd2bbf038c98dacfbe654f1a4d "Only
run meson from python when it apparently needs to be" (that had been removed
with df83ad933b11e973855d66792c9aff38714f9201 "fix harfbuzz build with
--enable-python=fully-internal on linux") to treat a Meson executable that
doesn't advertise itself as being a Python script as just any plain executable,
which we don't throw at our --enable-python=fully-internal interpreter.  (Just
like, say, an Emscripten build of LO uses an emcc compiler executable that
internally uses Python, and onto which we don't force our
--enable-python=fully-internal interpreter, either.)

Change-Id: I13965ef08043f350e9614bd61a469708b7faf27b
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/184626
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>