-Werror,-Wgnu-folding-constant
> desktop/unx/source/start.c:788:23: error: variable length array folded to constant array as an extension [-Werror,-Wgnu-folding-constant]
>   788 |             char resp[strlen("InternalIPC::SendArguments") + 1];
>       |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

since
<https://github.com/llvm/llvm-project/commit/e4163c0927772f2ec73cf16d53e000614c419c45>
"[clang] Emit bad shift warnings (#70307)" (and see the comments starting at
<https://github.com/llvm/llvm-project/pull/70307#issuecomment-2228342153>
"[clang] Emit bad shift warnings" for how this new warning is indeed
intentional)

Change-Id: Ie439a0f5f6f3b256fa82ec3a05fdc5fb3b840715
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/170510
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>
Tested-by: Jenkins