Fix non-pch build
C:/lo/core/cui/source/dialogs/fileextcheckdlg.cxx(53): error C2065:
'RET_OK': undeclared identifier

after commit 495fa42afab52b59ae283bb6c5a3992491d21214 (tdf#146619
Use more forward declarations in include/vcl/weld/, 2026-01-31).

Change-Id: I07a8a2487978fe92784e7c58540635e87323e44b
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/198463
Reviewed-by: Mike Kaganski <mike.kaganski@collabora.com>
Tested-by: Jenkins