Silence -Wdeprecated-pragma
...as seen with recent LLVM 19 trunk on macOS now,

> In file included from sal/osl/unx/uunxapi.mm:1:
> sal/osl/unx/uunxapi.cxx:612:14: error: macro 'ENOSTR' has been marked as deprecated: ENOSTR is deprecated in ISO C++ [-Werror,-Wdeprecated-pragma]
>   612 |         case ENOSTR:
>       |              ^
> ~/llvm/inst/bin/../include/c++/v1/cerrno:48:69: note: macro marked 'deprecated' here
>    48 | #  pragma clang deprecated(ENOSTR, "ENOSTR is deprecated in ISO C++")
>       |                                                                     ^

etc.  (And -Wdeprecated-pragma was only added towards Clang 14 with
<https://github.com/llvm/llvm-project/commit/26c695b7893071d5e69afbaa70c4850ab2e468be>
"Support macro deprecation #pragma clang deprecated", so wrap it in
__has_warning.)

Change-Id: I8db1f00a48bb647573d287c3410137182570f82b
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/165304
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>