tdf#130857 dbaccess: Show checkbox in front of icon in "Tables Filter" dlg
This is similar to previous commit

    Change-Id: I3a959d71cd91d5bfc20ba8abe50a3c7b1c189df3
    Author: Michael Weghorn <m.weghorn@posteo.de>
    Date:   Thu Jun 18 17:58:49 2026 +0200

        tdf#130857 dbaccess: Have special toggle before pixbuf col in dbtreelist.ui

and makes the order in which checkbox and icon are shown in
the Base "Tables Filter" dialog consistent between the gtk3
vcl plugin and other vcl plugins using the vcl
(SalInstanceTreeView) implementation, e.g. the gen vcl
plugin on Linux.

See the commit message of the above-mentioned commit for
more background.

Without this commit in place, gtk3 would show the
icons in front of the checkboxes to select which
tables to use while e.g. gen would show it the
other way around.

Sample steps to trigger the dialog:

* start Base
* create a new database
* switch to the "Tables" tab in Base
* create 2 tables, e.g. using "Create Table in Design View..."
* "Tools" -> "Table Filter..."

Now, gtk3 also shows the checkboxes in front
of the icons.

Mismatch in order was found by the ui-rules-enforcer
with upcoming commit

    Change-Id: I1f7c8c6456ed2e8ba4d8018d69fb12b40204536a
    Author: Michael Weghorn <m.weghorn@posteo.de>
    Date:   Thu Jun 18 17:25:19 2026 +0200

        ui-rules-enforcer: Check special treeview expander column order

in place:

    $ for a in `git ls-files "*.ui"`; do bin/ui-rules-enforcer.py $a; done
    Traceback (most recent call last):
      File "/home/michi/development/git/libreoffice/bin/ui-rules-enforcer.py", line 700, in <module>
        enforce_treeview_column_rules(root)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
      File "/home/michi/development/git/libreoffice/bin/ui-rules-enforcer.py", line 652, in enforce_treeview_column_rules
        enforce_treeview_column_rules(child)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
      File "/home/michi/development/git/libreoffice/bin/ui-rules-enforcer.py", line 652, in enforce_treeview_column_rules
        enforce_treeview_column_rules(child)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
      File "/home/michi/development/git/libreoffice/bin/ui-rules-enforcer.py", line 652, in enforce_treeview_column_rules
        enforce_treeview_column_rules(child)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
      [Previous line repeated 4 more times]
      File "/home/michi/development/git/libreoffice/bin/ui-rules-enforcer.py", line 665, in enforce_treeview_column_rules
        raise Exception(sys.argv[1] + ": treeview has special toggle and pixbuf columns/renderers in wrong order: ", current.attrib.get("id"))
    Exception: ('dbaccess/uiconfig/ui/tablesfilterpage.ui: treeview has special toggle and pixbuf columns/renderers in wrong order: ', 'treeview')

This is in preparation of reworking the handling
of the special expander columns a bit, also to prepare
support for more dialogs using them with
native Qt widgets as well.

Change-Id: Ie1bd0a96a79a9818f3aa573edb29e76363dbfe44
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/206985
Tested-by: Jenkins
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>