sfx2: Add missing include for SfxPoolItemHolder
Fixes this build failure seen in a local --enable-pch=no
Windows build:

	C:/Users/mwegh/development/git/libreoffice/sfx2/source/appl/appdde.cxx(148): error C2079: 'aResult' uses undefined class 'SfxPoolItemHolder'
	C:/Users/mwegh/development/git/libreoffice/sfx2/source/appl/appdde.cxx(148): error C2027: use of undefined type 'SfxPoolItemHolder'
	C:\Users\mwegh\development\git\libreoffice\include\sfx2/shell.hxx(53): note: see declaration of 'SfxPoolItemHolder'
	C:/Users/mwegh/development/git/libreoffice/sfx2/source/appl/appdde.cxx(152): error C2737: 'item': const object must be initialized
	C:/Users/mwegh/development/git/libreoffice/sfx2/source/appl/appdde.cxx(153): error C3536: 'item': cannot be used before it is initialized

Change-Id: I2c86c79d7381349bc24079c399b24f2df630fe07
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/200174
Tested-by: Jenkins
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>