UBSan CppunitTest_editeng_borderline etc. need more RTTI now
...presumably since 5ba893dfb8838b0ef946b52de9ef1336d2ab0512 "use more concrete
UNO type in editeng",

> DynamicLibraryManagerException: "Failed to load dynamic library: /home/tdf/lode/jenkins/workspace/lo_ubsan/workdir/LinkTarget/CppunitTest/libtest_editeng_borderline.so
> /home/tdf/lode/jenkins/workspace/lo_ubsan/instdir/program/libeditenglo.so: undefined symbol: _ZTIN3vcl9unohelper18DragAndDropWrapperE"

(<https://ci.libreoffice.org/job/lo_ubsan/3306/>)

Change-Id: I4501c3df9f353d9b1244f92b5bbc6fb2dafc24bd
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/173311
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>