Fix Windows x64 build
...after 6f45c0cf86b21772740bb0cafb3d462b058523f3 "cool#7318 Calc rendering
acceleration" caused

> sw/source/core/txtnode/fntcache.cxx(540): error C2672: 'std::min': no matching overloaded function found
> C:\PROGRA~1\MICROS~3\2022\Preview\VC\Tools\MSVC\1438~1.331\Include\utility(108): note: could be '_Ty std::min(std::initializer_list<_Elem>)'
> sw/source/core/txtnode/fntcache.cxx(540): note: '_Ty std::min(std::initializer_list<_Elem>)': expects 1 arguments - 2 provided
> C:\PROGRA~1\MICROS~3\2022\Preview\VC\Tools\MSVC\1438~1.331\Include\utility(105): note: or       '_Ty std::min(std::initializer_list<_Elem>,_Pr)'
> sw/source/core/txtnode/fntcache.cxx(540): note: '_Ty std::min(std::initializer_list<_Elem>,_Pr)': could not deduce template argument for 'std::initializer_list<_Elem>' from 'sal_Int32'
> C:\PROGRA~1\MICROS~3\2022\Preview\VC\Tools\MSVC\1438~1.331\Include\utility(98): note: or       'const _Ty &std::min(const _Ty &,const _Ty &) noexcept(<expr>)'
> sw/source/core/txtnode/fntcache.cxx(540): note: 'const _Ty &std::min(const _Ty &,const _Ty &) noexcept(<expr>)': template parameter '_Ty' is ambiguous
> sw/source/core/txtnode/fntcache.cxx(540): note: could be 'tools::Long'
> sw/source/core/txtnode/fntcache.cxx(540): note: or       'sal_Int32'
> sw/source/core/txtnode/fntcache.cxx(540): note: 'const _Ty &std::min(const _Ty &,const _Ty &) noexcept(<expr>)': could not deduce template argument for 'const _Ty &' from 'tools::Long'
> C:\PROGRA~1\MICROS~3\2022\Preview\VC\Tools\MSVC\1438~1.331\Include\utility(88): note: or       'const _Ty &std::min(const _Ty &,const _Ty &,_Pr) noexcept(<expr>)'
> sw/source/core/txtnode/fntcache.cxx(540): note: 'const _Ty &std::min(const _Ty &,const _Ty &,_Pr) noexcept(<expr>)': expects 3 arguments - 2 provided

Change-Id: I9af33041a81190998303aec2795fe03da7e2f119
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/157858
Tested-by: Jenkins
Reviewed-by: Mike Kaganski <mike.kaganski@collabora.com>