Fix UBSan build's RTTI needs
...after 0ed1cb5457a2106316f9d7fda10685360db4bc30 "make more symbols private in
writer" had caused CppunitTest_sw_odfimport to fail with

> DynamicLibraryManagerException: "Failed to load dynamic library: workdir/LinkTarget/CppunitTest/libtest_sw_odfimport.so
> workdir/LinkTarget/CppunitTest/libtest_sw_odfimport.so: undefined symbol: _ZTI14SwTransferable"

Change-Id: Ia6be10efb380b298488af351e85c5655254c3f63
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/164511
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>