UBSan needs SwXBookmark RTTI now
...presumably since 6a11bf9f7bd209a082254c861d5a04c7f5729d68 "use more concrete
UNO classes in writerfilter (SwXBookmark)", failing sw_writerfilter_misc with

> DynamicLibraryManagerException: "Failed to load dynamic library: workdir/LinkTarget/CppunitTest/libtest_sw_writerfilter_misc.so
> instdir/program/libsw_writerfilterlo.so: undefined symbol: _ZTI11SwXBookmark"

Change-Id: I9f839ca0f6986723cd2c4add5eaef3ac8ab8d841
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/166821
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>