sd: silence warning C6011: Dereferencing NULL pointer 'pPaintWindow'
C:/cygwin/home/tdf/lode/jenkins/workspace/lo_tb_master_win_analyze/sd/source/ui/tools/SlideshowLayerRenderer.cxx(770): error C2220: the following warning is treated as an error
C:\cygwin\home\tdf\lode\jenkins\workspace\lo_tb_master_win_analyze\sd\source\ui\tools\SlideshowLayerRenderer.cxx(768) : warning C6011: Dereferencing NULL pointer 'pPaintWindow'. : Lines: 741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 752, 753, 755, 762, 766, 767, 768
make[1]: *** [C:/cygwin/home/tdf/lode/jenkins/workspace/lo_tb_master_win_analyze/solenv/gbuild/LinkTarget.mk:339: C:/cygwin/home/tdf/lode/jenkins/workspace/lo_tb_master_win_analyze/workdir/CxxObject/sd/source/ui/tools/SlideshowLayerRenderer.o] Error 2

After
commit 7c76dfc35350d6a8fef0379129b17ab97a775a4a
Author: Marco Cecchetti <marco.cecchetti@collabora.com>
Date:   Tue Dec 3 18:59:50 2024 +0100

    lok: slideshow: handle text object in edit mode

Change-Id: I561ee1aa9f20c1c5de8f44efa547b1ad8069e370
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/183547
Tested-by: Jenkins
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>