external/graphite: operation between different enumeration types
> workdir/UnpackedTarball/graphite/src/Pass.cpp:197:92: error: invalid arithmetic between different enumeration types ('status_t' and 'graphite2::errors')
>   197 |                 || e.test(m_cPConstraint.status() != Code::loaded, m_cPConstraint.status() + E_CODEFAILURE))
>       |                                                                    ~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~

etc. as reported now with --with-latest-c++ (i.e., in C++26 mode) by Clang 18
trunk since
<https://github.com/llvm/llvm-project/commit/1cbd52f791d3f088246526c0801634edb65cee31>
"[Clang] Implement P2864R2 Remove Deprecated Arithmetic Conversion on
Enumerations (#73105)"

Change-Id: I34b2743d46b8f46b1f39b2af812f95876e4b9e38
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/160550
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>