workaround timing issue in UITest_writer_tests8 test_tdf145158
related to tdf#145158 - the test can fail on slow or loaded machines
since initially the control has the 2pt value, so when the test tries to
check whether the size is 12pt, it might do so too early and the test
will fail:

======================================================================
FAIL: test_tdf145158 (tdf145158.tdf145158.test_tdf145158)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tdf/lode/jenkins/workspace/lo_gerrit/Config/linux_gcc_release_64/sw/qa/uitest/writer_tests8/tdf145158.py", line 28, in test_tdf145158
    self.assertEqual("12 pt", get_state_as_dict(xFontsize)['Text'])
AssertionError: '12 pt' != '2 pt'
- 12 pt
? -
+ 2 pt

----------------------------------------------------------------------
Ran 28 tests in 33.743s

FAILED (failures=1, skipped=4)
Tests run: 28
Tests failed: 1
Tests errors: 0
Tests skipped: 4
tearDown: calling terminate()...
...done

Adding the waitUntilAllIdlesDispatched() call avoids this problem

Change-Id: Ibb2aec7dfdab887ca75841e99d879402a020de3e
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/186268
Tested-by: Jenkins
Tested-by: Christian Lohmaier <lohmaier+LibreOffice@googlemail.com>
Reviewed-by: Christian Lohmaier <lohmaier+LibreOffice@googlemail.com>