GCC 15 trunk now defaults to C23, where bool is a keyword
...so the existing C code started to fail with

> In file included from workdir/UnpackedTarball/mariadb-connector-c/libmariadb/ma_alloc.c:20:
> workdir/UnpackedTarball/mariadb-connector-c/include/ma_global.h:687:25: error: two or more data types in declaration specifiers
>   687 | typedef char            bool;   /* Ordinary boolean values 0 1 */
>       |                         ^~~~

(And the !defined(HAVE_BOOL) there, always being true, apparently started to get
in the way now and thus needed to be removed, whatever its original purpose.)

Change-Id: I781458d643e01a7199e19a178da3a32520d16b34
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/177260
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>
Tested-by: Jenkins