vcl: Report new Platform::Windows on Windows
Now that

    Change-Id: I383ad8ab287680f1d50dfc65d7d4d83eab3af5c8
    Author: Michael Weghorn <m.weghorn@posteo.de>
    Date:   Thu Mar 12 12:28:43 2026 +0100

        vcl: Get Platform from SalInstance, not SystemEnvData

moved the logic to report the platform to SalInstance,
introduce a new Platform::Windows enum value and
report it on Windows instead of the more generic
Platform::Other.

This will also come in handy when extending the logic
in the qt6 VCL plugin in order to support Windows as well
(see WIP change at [1]). Already extend the logic in the
corresponding QtFrame and QtInstance methods to handle
the new enum value to avoid

    .../vcl/qt5/QtFrame.cxx:255:29: error: enumeration value 'Windows' not handled in switch [-Werror,-Wswitch]
      255 |     switch (GetQtInstance().GetPlatform())
          |             ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~

https: //gerrit.libreoffice.org/c/core/+/199615
Change-Id: If8792c007f3792975ab65fc89a998117d4a0a6b7
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/201538
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>
Tested-by: Jenkins