Fix Windows Qt build
 ## Issue

Build errors can be seen on Windows:

```
C:\sources\lo\libo-core\vcl\qt6../qt5/QtFrame.cxx(682): error C2065: 'm_SessionManagerInhibitor': undeclared identifier
C:\sources\lo\libo-core\vcl\qt6../qt5/QtFrame.cxx(682): error C2065: 'APPLICATION_INHIBIT_IDLE': undeclared identifier
```

 ## Root cause

The build errors occur because the code is trying to use m_SessionManagerInhibitor and APPLICATION_INHIBIT_IDLE on platforms where they're not defined. These symbols are only available on Unix-like systems (Linux, Solaris, FreeBSD, OpenBSD).

 ## Fix

Revert change from commit 811769f009ec431ba622fc8a89eb1642dfd43568 which
replaced the proper if defined directive with __EMSCRIPTEN__

Change-Id: I1d15d96d0f971c7006ebf2caad8638fec2705007
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/206471
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>
Tested-by: Jenkins