solenv: Fix indentation in Python GDB pretty printer
Fix incorrect indentation causing

    Traceback (most recent call last):
      File "/home/michi/development/git/libreoffice/instdir/program/libbasegfxlo.so-gdb.py", line 23, in <module>
        module = importlib.import_module('libreoffice.' + mod)
      File "/usr/lib/python3.13/importlib/__init__.py", line 88, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
               ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
      File "<frozen importlib._bootstrap_external>", line 1160, in get_code
      File "<frozen importlib._bootstrap_external>", line 1090, in source_to_code
      File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
      File "/home/michi/development/git/libreoffice/solenv/gdb/libreoffice/basegfx.py", line 121
        if self.index >= self.count:
                                    ^
    IndentationError: unindent does not match any outer indentation level

since

    commit 221f9aa5828aad420d0599f5a24f71b7f83c9244
    Date:   Wed Mar 5 21:46:04 2025 +0100

        another try for Armin's problem with debuggers and pretty printers

Change-Id: I53330858c433ff4dd2b0dadce89ea955b3a014c9
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/182662
Tested-by: Jenkins
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>