sw: silence warning C6011: Dereferencing NULL pointer 'pCnt'
E:/jenkins/workspace/lo_tb_master_win_analyze/sw/source/uibase/utlui/content.cxx(3144): error C2220: the following warning is treated as an error
E:\jenkins\workspace\lo_tb_master_win_analyze\sw\source\uibase\utlui\content.cxx(3140) : warning C6011: Dereferencing NULL pointer 'pCnt'. : Lines: 3136, 3137, 3140

After
commit a66fd0b6d9300a7def03658c1661cb6d5f609ab9
Author: Jim Raykowski <raykowj@gmail.com>
Date:   Sun Dec 21 23:31:53 2025 -0900

    tdf#164864 SwNavigator should show index entries

Change-Id: Ib5f565b7b30fbdb8a8d78d6da305bffb43b93b7b
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/198189
Tested-by: Jenkins
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>