fix windows/aarch64 cross-compilation wrt skia
skia had been made mandatory for windows and along with that some
conditionals skipping skia headers were removed/those skia headers were
also made mandatory:

C:/cygwin64/home/tdf/jenkins/workspace/lo_daily_src/vcl/inc\skia/utils.hxx(34): fatal error C1083: Cannot open include file: 'SkRegion.h': No such file or directory

So also enable skia when building the cross-toolset when cross-compiling
for windows/aarch64 (not necessary for win/32 since the builder can run
the tools like gengal that are built for the host)

Change-Id: Ifa7cdf568dab7c9ea941548b1f4d64454241b0e7
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/187499
Tested-by: Jenkins
Reviewed-by: Christian Lohmaier <lohmaier+LibreOffice@googlemail.com>