external/firebird: Reinstate UBSan function-type-mismatch fix
...that had erroneously been removed by 00eae23267bf64e07cf057f828cd85f3c38ac669
"tdf#134526 Firebird: upgrade to release 3.0.11", causing

> workdir/UnpackedTarball/firebird/src/intl/cs_icu.cpp:66:30: runtime error: call to function ucnv_fromUChars_73 through pointer to incorrect function type 'int (*)(UConverter *, char *, int, const unsigned short *, int, UErrorCode *)'
> workdir/UnpackedTarball/icu/source/common/ucnv.cpp:1727: note: ucnv_fromUChars_73 defined here

etc. to reappear that had originally been fixed with
8336c1b579b6dff361e5422ebcdd225056752ed4 "New UBSan failures with Firebird
3.0.7".

Which then leads to the valid build failure

> workdir/UnpackedTarball/firebird/src/common/unicode_util.cpp:1381:25: error: no matching constructor for initialization of 'const Array<USHORT>' (aka 'const Array<unsigned short>')
>  1381 |                                 const Array<USHORT> str(strChars, prefixLen);
>       |                                                     ^   ~~~~~~~~~~~~~~~~~~~

so include a fix for that.

Change-Id: I30436b62d3adca511aa929317ac9cb7f31576382
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/161832
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <stephan.bergmann@allotropia.de>