vcl pdfwriter: Address some (suppressed) loplugin:stringadd errors
Address some of the logplugin:stringadd errors
in vcl/source/gdi/pdfwriter_impl.cxx, like

    /home/michi/development/git/libreoffice/vcl/source/gdi/pdfwriter_impl.cxx:581:5: error: simplify by merging with the preceding assign/append [loplugin:stringadd]
      581 |     aCreationMetaDateString.append(char('0' + ((aDT.Year / 100) % 10)));
          |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/michi/development/git/libreoffice/vcl/source/gdi/pdfwriter_impl.cxx:582:5: error: simplify by merging with the preceding assign/append [loplugin:stringadd]
      582 |     aCreationMetaDateString.append(char('0' + ((aDT.Year / 10) % 10)));
          |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/michi/development/git/libreoffice/vcl/source/gdi/pdfwriter_impl.cxx:583:5: error: simplify by merging with the preceding assign/append [loplugin:stringadd]
      583 |     aCreationMetaDateString.append(char('0' + ((aDT.Year) % 10)));
          |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/michi/development/git/libreoffice/vcl/source/gdi/pdfwriter_impl.cxx:584:5: error: simplify by merging with the preceding assign/append [loplugin:stringadd]
      584 |     aCreationMetaDateString.append("-");
          |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/michi/development/git/libreoffice/vcl/source/gdi/pdfwriter_impl.cxx:585:5: error: simplify by merging with the preceding assign/append [loplugin:stringadd]
      585 |     aCreationMetaDateString.append(char('0' + ((aDT.Month / 10) % 10)));
          |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/michi/development/git/libreoffice/vcl/source/gdi/pdfwriter_impl.cxx:586:5: error: simplify by merging with the preceding assign/append [loplugin:stringadd]
      586 |     aCreationMetaDateString.append(char('0' + ((aDT.Month) % 10)));
          |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/michi/development/git/libreoffice/vcl/source/gdi/pdfwriter_impl.cxx:587:5: error: simplify by merging with the preceding assign/append [loplugin:stringadd]
      587 |     aCreationMetaDateString.append("-");
          |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Such errors are currently suppressed with a TODO to handle those, but
could be seen with this temporary local change in addition,
in order to temporarily enable the plugin for this file:

    diff --git a/compilerplugins/clang/stringadd.cxx b/compilerplugins/clang/stringadd.cxx
    index 60e61f04a8bb..25fc55019c10 100644
    --- a/compilerplugins/clang/stringadd.cxx
    +++ b/compilerplugins/clang/stringadd.cxx
    @@ -62,9 +62,6 @@ public:
             // TODO the += depends on the result of the preceding assign, so can't merge
             if (fn == SRCDIR "/editeng/source/misc/svxacorr.cxx")
                 return false;
    -        // TODO this file has a boatload of buffer appends' and I don't feel like fixing them all now
    -        if (fn == SRCDIR "/vcl/source/gdi/pdfwriter_impl.cxx")
    -            return false;
             return true;
         }

In computeDocumentIdentifier, use OStringChar, based on
the suggestions in [1] and [2].

There are more of such plugin errors still left to address, so
leave the exception in place for now.

[1] https://gerrit.libreoffice.org/c/core/+/191122/1..10/vcl/source/gdi/pdfwriter_impl.cxx#b581
[2] https://lists.freedesktop.org/archives/libreoffice/2025-September/093812.html

Change-Id: If3f99c379157a2a2a6fac07116a0362fba62d944
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/191557
Tested-by: Jenkins
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>