CppunitTest_sw_globalfilter: fix test on Windows
gerrit_windows_wsl was configure to build with 'make build'
so this failure wasn't caught in time.
Now gerrit_windows_wsl builds with 'make build unitcheck slowcheck'
and it fails with
[_RUN_____] `anonymous namespace'::testTextFormField_ODT::TestBody
warn:vcl:12756:12144:vcl/win/window/salframe.cxx:1046: WinSalFrame::SetIcon(): Could not load large icon !
warn:vcl:12756:12144:vcl/win/window/salframe.cxx:1047: WinSalFrame::SetIcon(): Could not load small icon !
Throwing InvalidHeaderException
Throwing InvalidHeaderException
Throwing InvalidHeaderException
Throwing InvalidHeaderException
AbiDocument::isFileFormatSupported
Found xml parser severity error Start tag expected, '<' not found
Throwing InvalidHeaderException
warn:vcl:12756:12144:vcl/win/window/salframe.cxx:1046: WinSalFrame::SetIcon(): Could not load large icon !
warn:vcl:12756:12144:vcl/win/window/salframe.cxx:1047: WinSalFrame::SetIcon(): Could not load small icon !
file:///E:/jenkins/workspace/gerrit_windows_wsl/sw/qa/extras/globalfilter/data/text_form_field.odt:
file:///E:/jenkins/workspace/gerrit_windows_wsl/tmp/test_sw_globalfilter.dllbk795.tmp:
`anonymous namespace'::testTextFormField_ODT::TestBody finished in: 1608ms
E:/jenkins/workspace/gerrit_windows_wsl/sw/qa/extras/globalfilter/globalfilter.cxx(1432) : error : Assertion
Test name: `anonymous namespace'::testListLabelPDFExport::TestBody
equality assertion failed
- Expected: 22
- Actual  : 10

Change-Id: I005aa5cf269c81f8ddc98b3cc869c09348fb4c00
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/208187
Tested-by: Xisco Fauli <xiscofauli@libreoffice.org>
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>