Revert "skia: drop unneeded patch"
This reverts commit 3324e909e8c5251b30a21bd781da1d6229478a16.

Reason for revert: still needed
https://ci.libreoffice.org/job/lo_tb_master_win_analyze/ fails with
E:\jenkins\workspace\lo_tb_master_win_analyze\workdir\UnpackedTarball\skia\include/core/SkString.h(34): error C2220: the following warning is treated as an error
E:\jenkins\workspace\lo_tb_master_win_analyze\workdir\UnpackedTarball\skia\include\core\SkString.h(33) : warning C6011: Dereferencing NULL pointer 'string'. : Lines: 32, 33
[build CXX] vcl/win/gdi/winlayout.cxx

Change-Id: I1b6d7e2920df6e267b1e215c820b848f3997d3a6
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/199896
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>
Tested-by: Jenkins