fix linking error
seen by David Gilbert:
/usr/bin/ld: /discs/fast/core/workdir/CxxObject/sc/source/ui/vba/vbaeventshelper.o: in function `com::sun::star::uno::Reference<com::sun::star::sheet::XSheetCellRangeContainer>::Reference(com::sun::star::sheet::XSheetCellRangeContainer*)':
/discs/fast/core/include/com/sun/star/uno/Reference.hxx:161: undefined reference to `non-virtual thunk to ScCellRangesObj::acquire()'

after
    commit 3ba92b5f1eaf7d4447a0943ea260db515ca799dc
    Author: Noel Grandin <noel.grandin@collabora.co.uk>
    Date:   Thu Feb 15 10:04:51 2024 +0200
    hide more symbols

Change-Id: Id5e21aec323c2779ded464b6a0f8428705dfd0ab
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/163663
Tested-by: Jenkins
Reviewed-by: Noel Grandin <noel.grandin@collabora.co.uk>